# DataFrame
## Jest to zbiór danych, które znajdują się w więcej niż 2 kolumnach. 
## Możemy wykonywać metody i atrybuty na: samej dataFrame, dwóch dataFrame'ach, dateFrame oraz dataSeries, dataFrame oraz slowniku

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

## Pobieranie danych z miejsca, w którym znajduje się plik jupyter

In [7]:
mcd = pd.read_csv("./data/mcdonalds.csv")

### Pobieranie części kolumn z pliku 

In [9]:
mcdSelected = pd.read_csv("./data/mcdonalds.csv", usecols=["Item","Serving Size", "Calories from Fat", "TotalFat"])

### Pobranie i określenie, która kolumna ma być indexem ( index_col=["zzz"] )

In [10]:
mcdSelectedIndex = pd.read_csv("./data/mcdonalds.csv", usecols=["Item", "TotalFat"], index_col=["Item"])

# Podstawowe funkcje 

### type(dataFrame)

In [61]:
type(mcd)

pandas.core.frame.DataFrame

### funckja .head(wartość) 
wyświetla (wartość) pierwszych wartości

In [5]:
mcd.head()

Category                              Item    Serving Size  Calories  \
0  Breakfast                      Egg McMuffin  4.8 oz (136 g)       300   
1  Breakfast                 Egg White Delight  4.8 oz (135 g)       250   
2  Breakfast                  Sausage McMuffin  3.9 oz (111 g)       370   
3  Breakfast         Sausage McMuffin with Egg  5.7 oz (161 g)       450   
4  Breakfast  Sausage McMuffin with Egg Whites  5.7 oz (161 g)       400   

   Calories from Fat  TotalFat  Total Fat (% Daily Value)  Saturated Fat  \
0                120      13.0                         20            5.0   
1                 70       8.0                         12            3.0   
2                200      23.0                         35            8.0   
3                250      28.0                         43           10.0   
4                210      23.0                         35            8.0   

   Saturated Fat (% Daily Value)  Trans Fat  ...  Carbohydrates  \
0                             25        0.0  ...             31   
1                             15        0.0  ...             30   
2                             42        0.0  ...             29   
3                             52        0.0  ...             30   
4                             42        0.0  ...             30   

   Carbohydrates (% Daily Value)  Dietary Fiber  \
0                             10              4   
1                             10              4   
2                             10              4   
3                             10              4   
4                             10              4   

   Dietary Fiber (% Daily Value)  Sugars  Protein  Vitamin A (% Daily Value)  \
0                             17       3       17                         10   
1                             17       3       18                          6   
2                             17       2       14                          8   
3                             17       2       21                         15   
4                             17       2       21                          6   

   Vitamin C (% Daily Value)  Calcium (% Daily Value)  Iron (% Daily Value)  
0                          0                       25                    15  
1                          0                       25                     8  
2                          0                       25                    10  
3                          0                       30                    15  
4                          0                       25                    10  

[5 rows x 24 columns]

### funckja .tail(wartość)
wyświetla (wartość) ostatnich wartości

In [6]:
mcd.tail(10)

Category                                               Item  \
250  Smoothies & Shakes                            Shamrock Shake (Medium)   
251  Smoothies & Shakes                             Shamrock Shake (Large)   
252  Smoothies & Shakes                McFlurry with M&M’s Candies (Small)   
253  Smoothies & Shakes               McFlurry with M&M’s Candies (Medium)   
254  Smoothies & Shakes                McFlurry with M&M’s Candies (Snack)   
255  Smoothies & Shakes                 McFlurry with Oreo Cookies (Small)   
256  Smoothies & Shakes                McFlurry with Oreo Cookies (Medium)   
257  Smoothies & Shakes                 McFlurry with Oreo Cookies (Snack)   
258  Smoothies & Shakes  McFlurry with Reese's Peanut Butter Cups (Medium)   
259  Smoothies & Shakes   McFlurry with Reese's Peanut Butter Cups (Snack)   

        Serving Size  Calories  Calories from Fat  TotalFat  \
250     16 fl oz cup       660                170      19.0   
251     22 fl oz cup       820                210      23.0   
252  10.9 oz (310 g)       650                210      23.0   
253  16.2 oz (460 g)       930                290      33.0   
254   7.3 oz (207 g)       430                140      15.0   
255  10.1 oz (285 g)       510                150      17.0   
256  13.4 oz (381 g)       690                200      23.0   
257   6.7 oz (190 g)       340                100      11.0   
258  14.2 oz (403 g)       810                290      32.0   
259   7.1 oz (202 g)       410                150      16.0   

     Total Fat (% Daily Value)  Saturated Fat  Saturated Fat (% Daily Value)  \
250                         29           12.0                             61   
251                         35           15.0                             73   
252                         35           14.0                             72   
253                         50           20.0                            102   
254                         24           10.0                             48   
255                         26            9.0                             44   
256                         35           12.0                             58   
257                         17            6.0                             29   
258                         50           15.0                             76   
259                         25            8.0                             38   

     Trans Fat  ...  Carbohydrates  Carbohydrates (% Daily Value)  \
250        1.0  ...            109                             36   
251        1.0  ...            135                             45   
252        0.5  ...             96                             32   
253        1.0  ...            139                             46   
254        0.0  ...             64                             21   
255        0.5  ...             80                             27   
256        1.0  ...            106                             35   
257        0.0  ...             53                             18   
258        1.0  ...            114                             38   
259        0.0  ...             57                             19   

     Dietary Fiber  Dietary Fiber (% Daily Value)  Sugars  Protein  \
250              0                              0      93       14   
251              0                              0     115       18   
252              1                              6      89       13   
253              2                              7     128       20   
254              1                              4      59        9   
255              1                              4      64       12   
256              1                              5      85       15   
257              1                              2      43        8   
258              2                              9     103       21   
259              1                              5      51       10   

     Vitamin A (% Daily Value)  Vitamin C (% Daily

### .count()
Liczy znane(inne niż NaN) elementy w każdej kolumnie

In [11]:
mcd.count()

Category                         260
Item                             260
Serving Size                     260
Calories                         260
Calories from Fat                260
TotalFat                         260
Total Fat (% Daily Value)        260
Saturated Fat                    260
Saturated Fat (% Daily Value)    260
Trans Fat                        260
Cholesterol                      260
Cholesterol (% Daily Value)      260
Sodium                           260
Sodium (% Daily Value)           260
Carbohydrates                    260
Carbohydrates (% Daily Value)    260
Dietary Fiber                    260
Dietary Fiber (% Daily Value)    260
Sugars                           260
Protein                          260
Vitamin A (% Daily Value)        260
Vitamin C (% Daily Value)        260
Calcium (% Daily Value)          260
Iron (% Daily Value)             260
dtype: int64

### .len(nazwa dataFrame)
Liczy całkowitą długość dataFrame - ilość wierszy

In [12]:
len(mcd)

260

### .dtypes
Określa typ wszystkich kolumn (int, float, object itd)

In [13]:
mcd.dtypes

Category                          object
Item                              object
Serving Size                      object
Calories                           int64
Calories from Fat                  int64
TotalFat                         float64
Total Fat (% Daily Value)          int64
Saturated Fat                    float64
Saturated Fat (% Daily Value)      int64
Trans Fat                        float64
Cholesterol                        int64
Cholesterol (% Daily Value)        int64
Sodium                             int64
Sodium (% Daily Value)             int64
Carbohydrates                      int64
Carbohydrates (% Daily Value)      int64
Dietary Fiber                      int64
Dietary Fiber (% Daily Value)      int64
Sugars                             int64
Protein                            int64
Vitamin A (% Daily Value)          int64
Vitamin C (% Daily Value)          int64
Calcium (% Daily Value)            int64
Iron (% Daily Value)               int64
dtype: object

### .dtypes.value_counts()
Liczy ile jest kolumn danego typu ( ile int, ile object itd.)

In [14]:
mcd.dtypes.value_counts()

int64      18
object      3
float64     3
dtype: int64

### .shape
Wyświetla ilość wierszy i kolumn

In [15]:
mcd.shape

(260, 24)

### .axes 
Zwraca wartości indexów, oraz kolumn 
W tym przykladzie indexy są numeryczne, więc RangeIndex(start=0, stop=260, step=1), natomiast kolumny są objectami, więc są wypisane


In [16]:
mcd.axes

[RangeIndex(start=0, stop=260, step=1),
 Index(['Category', 'Item', 'Serving Size', 'Calories', 'Calories from Fat',
        'TotalFat', 'Total Fat (% Daily Value)', 'Saturated Fat',
        'Saturated Fat (% Daily Value)', 'Trans Fat', 'Cholesterol',
        'Cholesterol (% Daily Value)', 'Sodium', 'Sodium (% Daily Value)',
        'Carbohydrates', 'Carbohydrates (% Daily Value)', 'Dietary Fiber',
        'Dietary Fiber (% Daily Value)', 'Sugars', 'Protein',
        'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)',
        'Calcium (% Daily Value)', 'Iron (% Daily Value)'],
       dtype='object')]

### .index
Wyświetla indexy

In [17]:
mcd.index

RangeIndex(start=0, stop=260, step=1)

### .columns
Wyswietla kolumny

In [18]:
mcd.columns

Index(['Category', 'Item', 'Serving Size', 'Calories', 'Calories from Fat',
       'TotalFat', 'Total Fat (% Daily Value)', 'Saturated Fat',
       'Saturated Fat (% Daily Value)', 'Trans Fat', 'Cholesterol',
       'Cholesterol (% Daily Value)', 'Sodium', 'Sodium (% Daily Value)',
       'Carbohydrates', 'Carbohydrates (% Daily Value)', 'Dietary Fiber',
       'Dietary Fiber (% Daily Value)', 'Sugars', 'Protein',
       'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)',
       'Calcium (% Daily Value)', 'Iron (% Daily Value)'],
      dtype='object')

### .values
wyświetla wszystkie wartości w dataFrame podzielone według wierszy. Jest to lista, w której są listy z każdym wierszem

In [19]:
mcd.values

array([['Breakfast', 'Egg McMuffin', '4.8 oz (136 g)', ..., 0, 25, 15],
       ['Breakfast', 'Egg White Delight', '4.8 oz (135 g)', ..., 0, 25,
        8],
       ['Breakfast', 'Sausage McMuffin', '3.9 oz (111 g)', ..., 0, 25,
        10],
       ...,
       ['Smoothies & Shakes', 'McFlurry with Oreo Cookies (Snack)',
        '6.7 oz (190 g)', ..., 0, 25, 6],
       ['Smoothies & Shakes',
        "McFlurry with Reese's Peanut Butter Cups (Medium)",
        '14.2 oz (403 g)', ..., 0, 60, 6],
       ['Smoothies & Shakes',
        "McFlurry with Reese's Peanut Butter Cups (Snack)",
        '7.1 oz (202 g)', ..., 0, 30, 4]], dtype=object)

### .info()
Wyświetla informacje o dataFrame - jest to połączenie: .index, .count, .dtypes, .shape

In [27]:
mcd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Category                       260 non-null    object 
 1   Item                           260 non-null    object 
 2   Serving Size                   260 non-null    object 
 3   Calories                       260 non-null    int64  
 4   Calories from Fat              260 non-null    int64  
 5   TotalFat                       260 non-null    float64
 6   Total Fat (% Daily Value)      260 non-null    int64  
 7   Saturated Fat                  260 non-null    float64
 8   Saturated Fat (% Daily Value)  260 non-null    int64  
 9   Trans Fat                      260 non-null    float64
 10  Cholesterol                    260 non-null    int64  
 11  Cholesterol (% Daily Value)    260 non-null    int64  
 12  Sodium                         260 non-null    int

###  .value_counts()
Liczy ile razy występuje każda wartość
<br> Nie może być wykorzystana dla całego dataFrame. Trzeba wybrać kolumnę, w której chcemy zliczyć wartości

In [21]:
mcd["Category"].value_counts()

Coffee & Tea          95
Breakfast             42
Smoothies & Shakes    28
Chicken & Fish        27
Beverages             27
Beef & Pork           15
Snacks & Sides        13
Desserts               7
Salads                 6
Name: Category, dtype: int64

### .sample(n=x, axis="columns")
Losuje elementy (wieszy lub kolumn), aby dowiedzieć się czegoś o analizowanym dataFrame. .sample() zawsze daje inny wynik
<br>Domyślnie n = 1, axis="row"
<br> Możemy też zobaczyć ilość % występujących wartości w dataFrame .sample(frac0.05) wyświetl 5% wartości

In [22]:
mcd.sample(n=5)

Category                                  Item  \
103            Desserts                       Baked Apple Pie   
155        Coffee & Tea               Hazelnut Latte (Medium)   
36            Breakfast                  Hotcakes and Sausage   
253  Smoothies & Shakes  McFlurry with M&M’s Candies (Medium)   
26            Breakfast             Steak, Egg & Cheese Bagel   

        Serving Size  Calories  Calories from Fat  TotalFat  \
103    2.7 oz (77 g)       250                110      13.0   
155     16 fl oz cup       330                 90      10.0   
36    6.8 oz (192 g)       520                210      24.0   
253  16.2 oz (460 g)       930                290      33.0   
26    8.5 oz (241 g)       670                310      35.0   

     Total Fat (% Daily Value)  Saturated Fat  Saturated Fat (% Daily Value)  \
103                         19            7.0                             35   
155                         16            6.0                             30   
36                          37            7.0                             36   
253                         50           20.0                            102   
26                          53           13.0                             63   

     Trans Fat  ...  Carbohydrates  Carbohydrates (% Daily Value)  \
103        0.0  ...             32                             11   
155        0.0  ...             50                             17   
36         0.0  ...             61                             20   
253        1.0  ...            139                             46   
26         1.5  ...             56                             19   

     Dietary Fiber  Dietary Fiber (% Daily Value)  Sugars  Protein  \
103              4                             15      13        2   
155              1                              4      47       11   
36               3                             10      14       15   
253              2                              7     128       20   
26               3                             12       7       33   

     Vitamin A (% Daily Value)  Vitamin C (% Daily Value)  \
103                          4                         25   
155                         10                          0   
36                           0                          0   
253                         25                          0   
26                          20                          4   

     Calcium (% Daily Value)  Iron (% Daily Value)  
103                        2                     6  
155                       35                     0  
36                        15                    15  
253                       70                    10  
26                        25                    25  

[5 rows x 24 columns]

# Ćwiczenie 
002. Metody i atrybuty

In [28]:
import pandas as pd

In [29]:
fuel = pd.read_csv("./data/fuel.csv", usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'])

In [30]:
fuel.head()

Vehicle ID  Year        Make               Model  \
0       26587  1984  Alfa Romeo           GT V6 2.5   
1       27705  1984  Alfa Romeo           GT V6 2.5   
2       26561  1984  Alfa Romeo  Spider Veloce 2000   
3       27681  1984  Alfa Romeo  Spider Veloce 2000   
4       27550  1984  AM General   DJ Po Vehicle 2WD   

                         Class Fuel Type  Combined MPG (FT1)  
0             Minicompact Cars   Regular                20.0  
1             Minicompact Cars   Regular                20.0  
2                  Two Seaters   Regular                21.0  
3                  Two Seaters   Regular                21.0  
4  Special Purpose Vehicle 2WD   Regular                17.0

In [32]:
fuel.dtypes

Vehicle ID              int64
Year                    int64
Make                   object
Model                  object
Class                  object
Fuel Type              object
Combined MPG (FT1)    float64
dtype: object

In [38]:
 fuel.dtypes.value_counts()

object     4
int64      2
float64    1
dtype: int64

In [40]:
fuel["Make"].value_counts().head(10)

Chevrolet        3389
Ford             2721
Dodge            2361
GMC              2174
Toyota           1599
BMW              1180
Nissan           1082
Mercedes-Benz     948
Mitsubishi        937
Pontiac           893
Name: Make, dtype: int64

In [51]:
fuel.index

RangeIndex(start=0, stop=31684, step=1)

In [53]:
fuel.columns

Index(['Vehicle ID', 'Year', 'Make', 'Model', 'Class', 'Fuel Type',
       'Combined MPG (FT1)'],
      dtype='object')

In [54]:
fuel.values

array([[26587, 1984, 'Alfa Romeo', ..., 'Minicompact Cars', 'Regular',
        20.0],
       [27705, 1984, 'Alfa Romeo', ..., 'Minicompact Cars', 'Regular',
        20.0],
       [26561, 1984, 'Alfa Romeo', ..., 'Two Seaters', 'Regular', 21.0],
       ...,
       [32065, 2012, 'Mitsubishi', ..., 'Compact Cars', 'Premium', 19.0],
       [32064, 2012, 'Mitsubishi', ..., 'Compact Cars', 'Premium', 19.0],
       [32106, 2012, 'Mitsubish', ..., nan, nan, nan]], dtype=object)

In [57]:
fuel.axes

[RangeIndex(start=0, stop=31684, step=1),
 Index(['Vehicle ID', 'Year', 'Make', 'Model', 'Class', 'Fuel Type',
        'Combined MPG (FT1)'],
       dtype='object')]

In [58]:
fuel.shape

(31684, 7)

In [59]:
fuel.count()

Vehicle ID            31684
Year                  31684
Make                  31684
Model                 31683
Class                 31683
Fuel Type             31683
Combined MPG (FT1)    31683
dtype: int64

In [60]:
len(fuel)

31684

### Wyświetlamy wszystkie wartości dla elementów, które w kolumnie make mają wartość Pontiac

In [90]:
fuel.where(fuel["Make"] == "Pontiac").dropna()

Vehicle ID    Year     Make Model                 Class Fuel Type  \
1600      26746.0  1984.0  Pontiac  1000       Subcompact Cars   Regular   
1601      26749.0  1984.0  Pontiac  1000       Subcompact Cars    Diesel   
1602      27844.0  1984.0  Pontiac  1000       Subcompact Cars   Regular   
1603      26747.0  1984.0  Pontiac  1000       Subcompact Cars   Regular   
1604      27845.0  1984.0  Pontiac  1000       Subcompact Cars   Regular   
...           ...     ...      ...   ...                   ...       ...   
29473     26444.0  2010.0  Pontiac  Vibe  Small Station Wagons   Regular   
29474     26446.0  2010.0  Pontiac  Vibe  Small Station Wagons   Regular   
29475     26442.0  2010.0  Pontiac  Vibe  Small Station Wagons   Regular   
29476     26443.0  2010.0  Pontiac  Vibe  Small Station Wagons   Regular   
29477     26445.0  2010.0  Pontiac  Vibe  Small Station Wagons   Regular   

       Combined MPG (FT1)  
1600                 26.0  
1601                 30.0  
1602                 24.0  
1603                 27.0  
1604                 25.0  
...                   ...  
29473                22.0  
29474                24.0  
29475                28.0  
29476                28.0  
29477                24.0  

[893 rows x 7 columns]

# Kolejne funkcje i metody

### .nazwakolumny 
wyświetla pojedyncze kolumny z dataFrame
<br> wyświetlenie pojedynczej kolumny zmieni typ data na dataSeries

In [67]:
mcd.Calories 

0      300
1      250
2      370
3      450
4      400
      ... 
255    510
256    690
257    340
258    810
259    410
Name: Calories, Length: 260, dtype: int64

Jeśli wyświetlimy pojedynczą kolumnę i typ danych zmieni się na dataSeries, to będziemy mogli korzystać z funkcji i metod z dataSeries

In [74]:
mcd.Calories.mean()


368.2692307692308

In [73]:
mcd.Calories.median()


340.0

In [72]:
mcd.Calories.max()

1880

Produkt z największą ilością kalorii ma ich 1880

In [75]:
mcd.Calories.idxmax()

82

I znajduje się na 82 Indexie, dlatego 

In [76]:
mcd.Item[82]

'Chicken McNuggets (40 piece)'

Teraz wiemy, że Chicken McNuggers (40 piece) ma 1880 kalorii i jest najbardziej kalorycznym produktem w mcd

Żeby wszystko wyznaczyć w jednym wierszu:

In [77]:
mcd.Item[mcd.Calories.idxmax()]

'Chicken McNuggets (40 piece)'

Czyli. z dataFrame mcd wybierz wartość z kolumny Item (bo chcemy nazwę produktu) i w [] musimy wpisać funkcję, która wyznaczy 
nr indexu, na której znajduje się produkt z największą ilościa kalorii, czyli idmax() w kolumnie Calories w dataFrame mcd

### dataFrame["NazwaKolumny"]
Działa tak samo jak dataFrame.nazwaKolumy, ale jest częściej stosowana i czytelniejsza
<br><br> Możemy przypisać kolumne do innej zmiennej i pobierać z niej dane

In [81]:
item = mcd["Item"]

In [82]:
item[241]

'Vanilla Shake (Small)'

In [83]:
item.loc[241]

'Vanilla Shake (Small)'

To samo możemy uzyskać bez przypisywania zmiennej 

In [84]:
mcd["Item"][241]

'Vanilla Shake (Small)'

Wyświetliło 241 element z kolumny Item, czyli Vanilla Shake. 
<br> To samo możemy uzyskać dzięki funkcji .loc(nr indexu, nazwa kolumny)

In [86]:
mcd.loc[241, "Item"] 

'Vanilla Shake (Small)'

## Tworzenie nowego dataFrame z kolumn już wczytanego dataFrame
Tak jak poberaliśmy pojedynczą kolumnę, tak też pobieramy ich więcej wymieniając po przecinku. Z tą różnicą, że musimy zastosować podwójny []

In [87]:
mcd[["Item", "Calories", "Sugars"]]

Item  Calories  Sugars
0                                         Egg McMuffin       300       3
1                                    Egg White Delight       250       3
2                                     Sausage McMuffin       370       2
3                            Sausage McMuffin with Egg       450       2
4                     Sausage McMuffin with Egg Whites       400       2
..                                                 ...       ...     ...
255                 McFlurry with Oreo Cookies (Small)       510      64
256                McFlurry with Oreo Cookies (Medium)       690      85
257                 McFlurry with Oreo Cookies (Snack)       340      43
258  McFlurry with Reese's Peanut Butter Cups (Medium)       810     103
259   McFlurry with Reese's Peanut Butter Cups (Snack)       410      51

[260 rows x 3 columns]

# Ćwiczenie 
3. Pobieranie danych z Data Frame

In [94]:
import pandas as pd

In [95]:
fuel = pd.read_csv("./data/fuel.csv", usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'], low_memory="False", index_col="Vehicle ID")

In [96]:
fuel.head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27705       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
26561       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27705        Regular                20.0  
26561        Regular                21.0  
27681        Regular                21.0  
27550        Regular                17.0

In [97]:
fuel["Make"].head()

Vehicle ID
26587    Alfa Romeo
27705    Alfa Romeo
26561    Alfa Romeo
27681    Alfa Romeo
27550    AM General
Name: Make, dtype: object

In [100]:
fuel["Make"].value_counts().head()

Chevrolet    3389
Ford         2721
Dodge        2361
GMC          2174
Toyota       1599
Name: Make, dtype: int64

In [102]:
fuel.loc[1873]

Year                             1986
Make                       Mitsubishi
Model                         Starion
Class                 Subcompact Cars
Fuel Type                     Premium
Combined MPG (FT1)               19.0
Name: 1873, dtype: object

In [105]:
fuel["Combined MPG (FT1)"][1873]

19.0

In [106]:
fuel.loc[1873, "Combined MPG (FT1)"]

19.0

In [107]:
fuel["Combined MPG (FT1)"].max()

112.0

In [108]:
fuel["Combined MPG (FT1)"].idxmax()

31673

In [110]:
fuel.loc[31673]

Year                             2012
Make                       Mitsubishi
Model                          i-MiEV
Class                 Subcompact Cars
Fuel Type                 Electricity
Combined MPG (FT1)              112.0
Name: 31673, dtype: object

In [116]:
fuel.loc[fuel["Combined MPG (FT1)"].idxmax()]

Year                             2012
Make                       Mitsubishi
Model                          i-MiEV
Class                 Subcompact Cars
Fuel Type                 Electricity
Combined MPG (FT1)              112.0
Name: 31673, dtype: object

In [117]:
shortFuel = fuel[["Make","Model"]]
shortFuel.head()

Make               Model
Vehicle ID                                
26587       Alfa Romeo           GT V6 2.5
27705       Alfa Romeo           GT V6 2.5
26561       Alfa Romeo  Spider Veloce 2000
27681       Alfa Romeo  Spider Veloce 2000
27550       AM General   DJ Po Vehicle 2WD

# Dodawanie i usuwanie kolumn 

In [120]:
mcd = pd.read_csv("./data/mcdonalds.csv", usecols=["Item", "Category", "Calories", "TotalFat", "Sugars", "Protein", "Cholesterol"])

In [121]:
mcd.head()

Category                              Item  Calories  TotalFat  \
0  Breakfast                      Egg McMuffin       300      13.0   
1  Breakfast                 Egg White Delight       250       8.0   
2  Breakfast                  Sausage McMuffin       370      23.0   
3  Breakfast         Sausage McMuffin with Egg       450      28.0   
4  Breakfast  Sausage McMuffin with Egg Whites       400      23.0   

   Cholesterol  Sugars  Protein  
0          260       3       17  
1           25       3       18  
2           45       2       14  
3          285       2       21  
4           50       2       21

 ### Dodawanie 
 nazwaFrame["Nazwa nowej kolumny"] = nazwaframe.nazwakolumny + nazwaframe.nazwakolumny
 <br> utowrzymy nową kolumnę, której wartościami będą wyniki dodawania wartości z dwóch podanych kolumn

In [136]:
mcd["SugarAndFat"] = mcd.Sugars + mcd.TotalFat

In [137]:
mcd

Category                                               Item  \
0             Breakfast                                       Egg McMuffin   
1             Breakfast                                  Egg White Delight   
2             Breakfast                                   Sausage McMuffin   
3             Breakfast                          Sausage McMuffin with Egg   
4             Breakfast                   Sausage McMuffin with Egg Whites   
..                  ...                                                ...   
255  Smoothies & Shakes                 McFlurry with Oreo Cookies (Small)   
256  Smoothies & Shakes                McFlurry with Oreo Cookies (Medium)   
257  Smoothies & Shakes                 McFlurry with Oreo Cookies (Snack)   
258  Smoothies & Shakes  McFlurry with Reese's Peanut Butter Cups (Medium)   
259  Smoothies & Shakes   McFlurry with Reese's Peanut Butter Cups (Snack)   

     Calories  TotalFat  Cholesterol  Sugars  Protein  SugarAndFat  \
0         300      13.0          260       3       17         16.0   
1         250       8.0           25       3       18         11.0   
2         370      23.0           45       2       14         25.0   
3         450      28.0          285       2       21         30.0   
4         400      23.0           50       2       21         25.0   
..        ...       ...          ...     ...      ...          ...   
255       510      17.0           45      64       12         81.0   
256       690      23.0           55      85       15        108.0   
257       340      11.0           30      43        8         54.0   
258       810      32.0           60     103       21        135.0   
259       410      16.0           30      51       10         67.0   

     SugarAndProtein  
0                 20  
1                 21  
2                 16  
3                 23  
4                 23  
..               ...  
255               76  
256              100  
257               51  
258              124  
259               61  

[260 rows x 9 columns]

Lub dwuetapowo 

In [133]:
SugarAndProtein = mcd.Sugars + mcd.Protein

In [134]:
mcd["SugarAndProtein"] = SugarAndProtein

In [135]:
mcd

Category                                               Item  \
0             Breakfast                                       Egg McMuffin   
1             Breakfast                                  Egg White Delight   
2             Breakfast                                   Sausage McMuffin   
3             Breakfast                          Sausage McMuffin with Egg   
4             Breakfast                   Sausage McMuffin with Egg Whites   
..                  ...                                                ...   
255  Smoothies & Shakes                 McFlurry with Oreo Cookies (Small)   
256  Smoothies & Shakes                McFlurry with Oreo Cookies (Medium)   
257  Smoothies & Shakes                 McFlurry with Oreo Cookies (Snack)   
258  Smoothies & Shakes  McFlurry with Reese's Peanut Butter Cups (Medium)   
259  Smoothies & Shakes   McFlurry with Reese's Peanut Butter Cups (Snack)   

     Calories  TotalFat  Cholesterol  Sugars  Protein  SugarAndFat  \
0         300      13.0          260       3       17         16.0   
1         250       8.0           25       3       18         11.0   
2         370      23.0           45       2       14         25.0   
3         450      28.0          285       2       21         30.0   
4         400      23.0           50       2       21         25.0   
..        ...       ...          ...     ...      ...          ...   
255       510      17.0           45      64       12         81.0   
256       690      23.0           55      85       15        108.0   
257       340      11.0           30      43        8         54.0   
258       810      32.0           60     103       21        135.0   
259       410      16.0           30      51       10         67.0   

     SugarAndProtein  
0                 20  
1                 21  
2                 16  
3                 23  
4                 23  
..               ...  
255               76  
256              100  
257               51  
258              124  
259               61  

[260 rows x 9 columns]

Takie dodawanie kolumn zawsze doda kolumnę na końcu 
<br> 
### .insert()
<br> dodawanie kolumn pomiędzy inne kolumny 

In [138]:
mcd.insert(loc=2, column="SPF", value=mcd.Sugars + mcd.TotalFat + mcd.Protein)

In [139]:
mcd

Category                                               Item  \
0             Breakfast                                       Egg McMuffin   
1             Breakfast                                  Egg White Delight   
2             Breakfast                                   Sausage McMuffin   
3             Breakfast                          Sausage McMuffin with Egg   
4             Breakfast                   Sausage McMuffin with Egg Whites   
..                  ...                                                ...   
255  Smoothies & Shakes                 McFlurry with Oreo Cookies (Small)   
256  Smoothies & Shakes                McFlurry with Oreo Cookies (Medium)   
257  Smoothies & Shakes                 McFlurry with Oreo Cookies (Snack)   
258  Smoothies & Shakes  McFlurry with Reese's Peanut Butter Cups (Medium)   
259  Smoothies & Shakes   McFlurry with Reese's Peanut Butter Cups (Snack)   

       SPF  Calories  TotalFat  Cholesterol  Sugars  Protein  SugarAndFat  \
0     33.0       300      13.0          260       3       17         16.0   
1     29.0       250       8.0           25       3       18         11.0   
2     39.0       370      23.0           45       2       14         25.0   
3     51.0       450      28.0          285       2       21         30.0   
4     46.0       400      23.0           50       2       21         25.0   
..     ...       ...       ...          ...     ...      ...          ...   
255   93.0       510      17.0           45      64       12         81.0   
256  123.0       690      23.0           55      85       15        108.0   
257   62.0       340      11.0           30      43        8         54.0   
258  156.0       810      32.0           60     103       21        135.0   
259   77.0       410      16.0           30      51       10         67.0   

     SugarAndProtein  
0                 20  
1                 21  
2                 16  
3                 23  
4                 23  
..               ...  
255               76  
256              100  
257               51  
258              124  
259               61  

[260 rows x 10 columns]

loc - miejsce, w którym ma się pojawić kolumna
<br> column - nazwa kolumny 
<br> value - jakie wartości ma przyjąć

### Usuwanie / odejmowanie kolumn

In [140]:
del mcd["SugarAndProtein"]

In [141]:
mcd.head()

Category                              Item   SPF  Calories  TotalFat  \
0  Breakfast                      Egg McMuffin  33.0       300      13.0   
1  Breakfast                 Egg White Delight  29.0       250       8.0   
2  Breakfast                  Sausage McMuffin  39.0       370      23.0   
3  Breakfast         Sausage McMuffin with Egg  51.0       450      28.0   
4  Breakfast  Sausage McMuffin with Egg Whites  46.0       400      23.0   

   Cholesterol  Sugars  Protein  SugarAndFat  
0          260       3       17         16.0  
1           25       3       18         11.0  
2           45       2       14         25.0  
3          285       2       21         30.0  
4           50       2       21         25.0

In [142]:
mcd = mcd.drop(columns=["SugarAndFat"])

In [143]:
mcd

Category                                               Item  \
0             Breakfast                                       Egg McMuffin   
1             Breakfast                                  Egg White Delight   
2             Breakfast                                   Sausage McMuffin   
3             Breakfast                          Sausage McMuffin with Egg   
4             Breakfast                   Sausage McMuffin with Egg Whites   
..                  ...                                                ...   
255  Smoothies & Shakes                 McFlurry with Oreo Cookies (Small)   
256  Smoothies & Shakes                McFlurry with Oreo Cookies (Medium)   
257  Smoothies & Shakes                 McFlurry with Oreo Cookies (Snack)   
258  Smoothies & Shakes  McFlurry with Reese's Peanut Butter Cups (Medium)   
259  Smoothies & Shakes   McFlurry with Reese's Peanut Butter Cups (Snack)   

       SPF  Calories  TotalFat  Cholesterol  Sugars  Protein  
0     33.0       300      13.0          260       3       17  
1     29.0       250       8.0           25       3       18  
2     39.0       370      23.0           45       2       14  
3     51.0       450      28.0          285       2       21  
4     46.0       400      23.0           50       2       21  
..     ...       ...       ...          ...     ...      ...  
255   93.0       510      17.0           45      64       12  
256  123.0       690      23.0           55      85       15  
257   62.0       340      11.0           30      43        8  
258  156.0       810      32.0           60     103       21  
259   77.0       410      16.0           30      51       10  

[260 rows x 8 columns]

Funckja del usuwa na stałe w podanym dataFrame
<br> funkcja drop nie zmienia na stałe w dataFrame, więc jeśli chcemy na stałe zmienić dataFrame to musimy jeszcze raz przypisać funkcję do tego samego dataFrame lub wykorzystać parametr inplace = True

In [144]:
mcd.drop(columns="SPF", inplace=True)

In [145]:
mcd

Category                                               Item  \
0             Breakfast                                       Egg McMuffin   
1             Breakfast                                  Egg White Delight   
2             Breakfast                                   Sausage McMuffin   
3             Breakfast                          Sausage McMuffin with Egg   
4             Breakfast                   Sausage McMuffin with Egg Whites   
..                  ...                                                ...   
255  Smoothies & Shakes                 McFlurry with Oreo Cookies (Small)   
256  Smoothies & Shakes                McFlurry with Oreo Cookies (Medium)   
257  Smoothies & Shakes                 McFlurry with Oreo Cookies (Snack)   
258  Smoothies & Shakes  McFlurry with Reese's Peanut Butter Cups (Medium)   
259  Smoothies & Shakes   McFlurry with Reese's Peanut Butter Cups (Snack)   

     Calories  TotalFat  Cholesterol  Sugars  Protein  
0         300      13.0          260       3       17  
1         250       8.0           25       3       18  
2         370      23.0           45       2       14  
3         450      28.0          285       2       21  
4         400      23.0           50       2       21  
..        ...       ...          ...     ...      ...  
255       510      17.0           45      64       12  
256       690      23.0           55      85       15  
257       340      11.0           30      43        8  
258       810      32.0           60     103       21  
259       410      16.0           30      51       10  

[260 rows x 7 columns]

# Ćwiczenie 
4. Dodawanie i usuwanie kolumn

In [146]:
import pandas as pd

In [147]:
fuel = pd.read_csv("./data/fuel.csv", usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'], low_memory="False" )

In [148]:
fuel.head()

Vehicle ID  Year        Make               Model  \
0       26587  1984  Alfa Romeo           GT V6 2.5   
1       27705  1984  Alfa Romeo           GT V6 2.5   
2       26561  1984  Alfa Romeo  Spider Veloce 2000   
3       27681  1984  Alfa Romeo  Spider Veloce 2000   
4       27550  1984  AM General   DJ Po Vehicle 2WD   

                         Class Fuel Type  Combined MPG (FT1)  
0             Minicompact Cars   Regular                20.0  
1             Minicompact Cars   Regular                20.0  
2                  Two Seaters   Regular                21.0  
3                  Two Seaters   Regular                21.0  
4  Special Purpose Vehicle 2WD   Regular                17.0

In [153]:
fuel["Combined KPL"] = fuel["Combined MPG (FT1)"] * 1.609 / 3.78

In [154]:
fuel.head()

Vehicle ID  Year        Make               Model  \
0       26587  1984  Alfa Romeo           GT V6 2.5   
1       27705  1984  Alfa Romeo           GT V6 2.5   
2       26561  1984  Alfa Romeo  Spider Veloce 2000   
3       27681  1984  Alfa Romeo  Spider Veloce 2000   
4       27550  1984  AM General   DJ Po Vehicle 2WD   

                         Class Fuel Type  Combined MPG (FT1)  Combined KPL  
0             Minicompact Cars   Regular                20.0      8.513228  
1             Minicompact Cars   Regular                20.0      8.513228  
2                  Two Seaters   Regular                21.0      8.938889  
3                  Two Seaters   Regular                21.0      8.938889  
4  Special Purpose Vehicle 2WD   Regular                17.0      7.236243

In [155]:
fuel.insert(loc=4,column="liters per km", value = 100 / fuel["Combined KPL"])

In [156]:
fuel

Vehicle ID  Year        Make               Model  liters per km  \
0           26587  1984  Alfa Romeo           GT V6 2.5      11.746426   
1           27705  1984  Alfa Romeo           GT V6 2.5      11.746426   
2           26561  1984  Alfa Romeo  Spider Veloce 2000      11.187073   
3           27681  1984  Alfa Romeo  Spider Veloce 2000      11.187073   
4           27550  1984  AM General   DJ Po Vehicle 2WD      13.819325   
...           ...   ...         ...                 ...            ...   
31679       32060  2012  Mitsubishi              Lancer       9.397141   
31680       32063  2012  Mitsubishi          Lancer AWD       9.397141   
31681       32065  2012  Mitsubishi    Lancer Evolution      12.364659   
31682       32064  2012  Mitsubishi    Lancer Evolution      12.364659   
31683       32106  2012   Mitsubish                 NaN            NaN   

                             Class Fuel Type  Combined MPG (FT1)  Combined KPL  
0                 Minicompact Cars   Regular                20.0      8.513228  
1                 Minicompact Cars   Regular                20.0      8.513228  
2                      Two Seaters   Regular                21.0      8.938889  
3                      Two Seaters   Regular                21.0      8.938889  
4      Special Purpose Vehicle 2WD   Regular                17.0      7.236243  
...                            ...       ...                 ...           ...  
31679                 Compact Cars   Regular                25.0     10.641534  
31680                 Compact Cars   Regular                25.0     10.641534  
31681                 Compact Cars   Premium                19.0      8.087566  
31682                 Compact Cars   Premium                19.0      8.087566  
31683                          NaN       NaN                 NaN           NaN  

[31684 rows x 9 columns]

In [157]:
del fuel["Combined MPG (FT1)"]

In [159]:
fuel = fuel.drop(columns="Combined KPL")

In [160]:
fuel

Vehicle ID  Year        Make               Model  liters per km  \
0           26587  1984  Alfa Romeo           GT V6 2.5      11.746426   
1           27705  1984  Alfa Romeo           GT V6 2.5      11.746426   
2           26561  1984  Alfa Romeo  Spider Veloce 2000      11.187073   
3           27681  1984  Alfa Romeo  Spider Veloce 2000      11.187073   
4           27550  1984  AM General   DJ Po Vehicle 2WD      13.819325   
...           ...   ...         ...                 ...            ...   
31679       32060  2012  Mitsubishi              Lancer       9.397141   
31680       32063  2012  Mitsubishi          Lancer AWD       9.397141   
31681       32065  2012  Mitsubishi    Lancer Evolution      12.364659   
31682       32064  2012  Mitsubishi    Lancer Evolution      12.364659   
31683       32106  2012   Mitsubish                 NaN            NaN   

                             Class Fuel Type  
0                 Minicompact Cars   Regular  
1                 Minicompact Cars   Regular  
2                      Two Seaters   Regular  
3                      Two Seaters   Regular  
4      Special Purpose Vehicle 2WD   Regular  
...                            ...       ...  
31679                 Compact Cars   Regular  
31680                 Compact Cars   Regular  
31681                 Compact Cars   Premium  
31682                 Compact Cars   Premium  
31683                          NaN       NaN  

[31684 rows x 7 columns]

# Oczyszczanie danych

### .dropna()
Funckja dropna() w dataFrame domyślnie usunie wszystkie wiersze, w których brakuje chociaż jednej wartości 

### .dropna(how="all")
w tym przypadku wiersze zostaną usunięte tylko wtedy kiedy wszystkie wartości będą NaN. Domyślnie = "any"

### .dropna(subset=["TotalFat], how="any")
subset = wpisujemy listę kolumn, które mają być analizowane. Usuwa wiersz jeśli w wymienionych kolumnach znajdzie wartość NaN

### .dropna(axis="rows")
domyślnie axis = 0, czyli rows. Wtedy usuwane są wiersze 

### .dropna(axis="columns")
axis = 1  == axis ="columns" - wtedy usuwane są kolumny, w których będą jakieś wartości NaN

### .dropna(inplace="True")
usuwa na stałe w danym dataFrame bez przypisywania zmiennej. Domyślnie jest False

# Ćwiczenie 
5. Oczyszczanie danych dropna()

In [1]:
import pandas as pd
import numpy as np

In [2]:
fuel = pd.read_csv("./data/fuel.csv", usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'], index_col="Vehicle ID", low_memory=False)

In [3]:
fuel.head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27705       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
26561       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27705        Regular                20.0  
26561        Regular                21.0  
27681        Regular                21.0  
27550        Regular                17.0

In [4]:
fuel.loc[27705, "Class"] = np.NaN

In [5]:
fuel.loc[26561, "Class"] = np.NaN

In [6]:
fuel.loc[27550, "Fuel Type"] = np.NaN

In [7]:
fuel.head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27705       1984  Alfa Romeo           GT V6 2.5                          NaN   
26561       1984  Alfa Romeo  Spider Veloce 2000                          NaN   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27705        Regular                20.0  
26561        Regular                21.0  
27681        Regular                21.0  
27550            NaN                17.0

In [9]:
fuel.dropna().head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
28426       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   
27549       1984  AM General    FJ8c Post Office  Special Purpose Vehicle 2WD   
28425       1984  AM General    FJ8c Post Office  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27681        Regular                21.0  
28426        Regular                17.0  
27549        Regular                13.0  
28425        Regular                13.0

In [10]:
fuel.dropna(axis=1).head()

Year        Make
Vehicle ID                  
26587       1984  Alfa Romeo
27705       1984  Alfa Romeo
26561       1984  Alfa Romeo
27681       1984  Alfa Romeo
27550       1984  AM General

In [12]:
fuel.dropna(subset=["Class"]).head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   
28426       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   
27549       1984  AM General    FJ8c Post Office  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27681        Regular                21.0  
27550            NaN                17.0  
28426        Regular                17.0  
27549        Regular                13.0

In [13]:
fuel.head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27705       1984  Alfa Romeo           GT V6 2.5                          NaN   
26561       1984  Alfa Romeo  Spider Veloce 2000                          NaN   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27705        Regular                20.0  
26561        Regular                21.0  
27681        Regular                21.0  
27550            NaN                17.0

In [15]:
fuel.dropna(subset=["Class"], inplace=True)

In [16]:
fuel.head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   
28426       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   
27549       1984  AM General    FJ8c Post Office  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27681        Regular                21.0  
27550            NaN                17.0  
28426        Regular                17.0  
27549        Regular                13.0

## Metoda .fillna()
Metoda, która pozwala uzupelniać brakujące dane

### fillna(value=None, method=None, axis=None, inplace=False, limit=None)
takie są wartości domyślne metody .fillna()
<br> value= wartość jaką chcemy wpisać zamiast NaN (np. 0 lub jakiś napis)
<br> 

Żeby określiś lepiej wartości jakie chcemy mieć w konkretnych kolumnach, możemy stworzyć słownik, gdzie kluczami będą nazwy kolumn, a wartościami wartości, które chcemy mieć w konkretnych kolumnach zamiast NaN. Taki słonik później przypisujemy do wartości value w metodzie .fillna()

In [17]:
replaceDefinitionTable = {"Category":"UNKNOW", "TotalFat":0,"Saturated Fat":0}

In [18]:
replaceDefinitionTable

{'Category': 'UNKNOW', 'TotalFat': 0, 'Saturated Fat': 0}

In [ ]:
dataFrame.fillna(value=replaceDefinitionTable).head()

Zamieni wartości NaN w podanych kolumnach na podane wartości. 

### .fillna() tylko w jednej kolumnie

In [ ]:
dataFrame["Category"].fillna(value="UNKNOW", inplace=True)

### przypisywanie średniej zamiast wartości NaN
wyliczamy średnią w nowej zmiennej --> zmienną wstawiamy jako value w metodzie .fillna()

In [19]:
avgTotalFat = dataFrame["TotalFat"].mean()

NameError: name 'mcd' is not defined

In [ ]:
dataFrame["TotalFat"].fillna(avgTotalFat, inplace=True)

### .fillna(method=)
method="ffill" - uzupełni wartości NaN wartością z wiersza powyżej. Wczęsniej warto posortować dataFrame po innej kolumnie, dzięki której ta kolumna z brakowymi wartościami będzie najbardziej zbliżona do wartości, która tam powinna być.
<br> method="bfill" uzupełni dane kolejną wartością ? nie potwierdzone

In [ ]:
dataFrame["Saturated Fat"].fillna(method="ffill", inplace=True)

# Ćwiczenie
6. Oczyszczanie danych .fillna()

In [21]:
import pandas as pd
import numpy as np

In [22]:
fuel = pd.read_csv("./data/fuel.csv", usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'], index_col="Vehicle ID", low_memory=False)

In [61]:
fuel.loc[27705, 'Class'] = np.NaN

In [62]:
fuel.loc[26561, 'Class'] = np.NaN

In [63]:
fuel.loc[27550, 'Fuel Type'] = np.NaN

In [64]:
fuel.loc[27705, 'Combined MPG (FT1)'] = np.NaN

In [65]:
fuel.loc[27681, 'Combined MPG (FT1)'] = np.NaN

In [28]:
fuel.head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27705       1984  Alfa Romeo           GT V6 2.5                          NaN   
26561       1984  Alfa Romeo  Spider Veloce 2000                          NaN   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27705        Regular                 NaN  
26561        Regular                21.0  
27681        Regular                 NaN  
27550            NaN                17.0

In [38]:
fuel.fillna(value=-1).head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27705       1984  Alfa Romeo           GT V6 2.5                           -1   
26561       1984  Alfa Romeo  Spider Veloce 2000                           -1   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27705        Regular                -1.0  
26561        Regular                21.0  
27681        Regular                -1.0  
27550             -1                17.0

In [43]:
replaceRules = {"Class":"---","Fuel Type":"---","Combined MPG (FT1)":-1}

In [44]:
fuel.fillna(value=replaceRules).head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27705       1984  Alfa Romeo           GT V6 2.5                          ---   
26561       1984  Alfa Romeo  Spider Veloce 2000                          ---   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27705        Regular                -1.0  
26561        Regular                21.0  
27681        Regular                -1.0  
27550            ---                17.0

In [45]:
avgMPG = fuel["Combined MPG (FT1)"].mean()

In [46]:
avgMPG

19.444177898424922

In [49]:
fuel["Class"].fillna(value="?", inplace=True)

In [50]:
fuel["Fuel Type"].fillna(value="?", inplace=True)

In [51]:
fuel["Combined MPG (FT1)"].fillna(value=avgMPG, inplace=True)

In [58]:
fuel.head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27705       1984  Alfa Romeo           GT V6 2.5                          NaN   
26561       1984  Alfa Romeo  Spider Veloce 2000                          NaN   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27705        Regular                 NaN  
26561        Regular                21.0  
27681        Regular                 NaN  
27550            NaN                17.0

In [66]:
fuel["Combined MPG (FT1)"].fillna(method="ffill", inplace=True)

In [67]:
fuel.head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27705       1984  Alfa Romeo           GT V6 2.5                          NaN   
26561       1984  Alfa Romeo  Spider Veloce 2000                          NaN   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27705        Regular                20.0  
26561        Regular                21.0  
27681        Regular                21.0  
27550            NaN                17.0

# Sortowanie danych 


In [68]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math

In [70]:
mcd = pd.read_csv("./data/mcdonalds.csv", usecols=["Item","Category", "Serving Size", "Calories", "TotalFat"])

In [71]:
mcd.head()

Category                              Item    Serving Size  Calories  \
0  Breakfast                      Egg McMuffin  4.8 oz (136 g)       300   
1  Breakfast                 Egg White Delight  4.8 oz (135 g)       250   
2  Breakfast                  Sausage McMuffin  3.9 oz (111 g)       370   
3  Breakfast         Sausage McMuffin with Egg  5.7 oz (161 g)       450   
4  Breakfast  Sausage McMuffin with Egg Whites  5.7 oz (161 g)       400   

   TotalFat  
0      13.0  
1       8.0  
2      23.0  
3      28.0  
4      23.0

### .sort_values()
.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')
<br> by - koluma lub kolumny, po których będziemy sortować 
<br> axis - 0 względem wierszy, 1 - wzgledem kolumn
<br> ascending - True -rosnąco, False - malejąco
<br> kind - algorytm jaki będzie wykorzystany
<br> na_position - mówi o tym jak będą traktowane wartości NaN (last - na koniec, czyli jako największa wartość; first - jako najmniejsza)

In [72]:
mcd.sort_values(by="Calories").head()

Category                    Item  Serving Size  Calories  TotalFat
125     Beverages  Diet Dr Pepper (Child)  12 fl oz cup         0       0.0
138  Coffee & Tea       Iced Tea (Medium)  21 fl oz cup         0       0.0
137  Coffee & Tea        Iced Tea (Small)  16 fl oz cup         0       0.0
136     Beverages     Dasani Water Bottle    16.9 fl oz         0       0.0
145  Coffee & Tea          Coffee (Small)  12 fl oz cup         0       0.0

In [73]:
mcd.sort_values(by="Calories", ascending=False).head()

Category                                               Item  \
82  Chicken & Fish                       Chicken McNuggets (40 piece)   
32       Breakfast        Big Breakfast with Hotcakes (Large Biscuit)   
31       Breakfast      Big Breakfast with Hotcakes (Regular Biscuit)   
34       Breakfast  Big Breakfast with Hotcakes and Egg Whites (La...   
33       Breakfast  Big Breakfast with Hotcakes and Egg Whites (Re...   

       Serving Size  Calories  TotalFat  
82  22.8 oz (646 g)      1880     118.0  
32  15.3 oz (434 g)      1150      60.0  
31  14.8 oz (420 g)      1090      56.0  
34  15.4 oz (437 g)      1050      50.0  
33  14.9 oz (423 g)       990      46.0

In [74]:
mcd.sort_values(by=["Category", "Item"]).head(20)

Category                                       Item  \
51   Beef & Pork                     Bacon Clubhouse Burger   
53   Beef & Pork                             Bacon McDouble   
42   Beef & Pork                                    Big Mac   
49   Beef & Pork                               Cheeseburger   
54   Beef & Pork                               Daily Double   
50   Beef & Pork                        Double Cheeseburger   
47   Beef & Pork         Double Quarter Pounder with Cheese   
48   Beef & Pork                                  Hamburger   
55   Beef & Pork                            Jalapeño Double   
52   Beef & Pork                                   McDouble   
56   Beef & Pork                                      McRib   
46   Beef & Pork                     Quarter Pounder Deluxe   
44   Beef & Pork        Quarter Pounder with Bacon & Cheese   
45   Beef & Pork  Quarter Pounder with Bacon Habanero Ranch   
43   Beef & Pork                Quarter Pounder with Cheese   
130    Beverages                        1% Low Fat Milk Jug   
113    Beverages                  Coca-Cola Classic (Child)   
112    Beverages                  Coca-Cola Classic (Large)   
111    Beverages                 Coca-Cola Classic (Medium)   
110    Beverages                  Coca-Cola Classic (Small)   

          Serving Size  Calories  TotalFat  
51      9.5 oz (270 g)       720      40.0  
53      5.7 oz (161 g)       440      22.0  
42      7.4 oz (211 g)       530      27.0  
49        4 oz (113 g)       290      11.0  
54      6.7 oz (190 g)       430      22.0  
50      5.7 oz (161 g)       430      21.0  
47       10 oz (283 g)       750      43.0  
48       3.5 oz (98 g)       240       8.0  
55      5.6 oz (159 g)       430      23.0  
52      5.2 oz (147 g)       380      17.0  
56      7.3 oz (208 g)       500      26.0  
46      8.6 oz (244 g)       540      27.0  
44        8 oz (227 g)       600      29.0  
45      8.3 oz (235 g)       610      31.0  
43      7.1 oz (202 g)       520      26.0  
130  1 carton (236 ml)       100       2.5  
113       12 fl oz cup       100       0.0  
112       30 fl oz cup       280       0.0  
111       21 fl oz cup       200       0.0  
110       16 fl oz cup       140       0.0

Sortowanie pierwszej kolumny rosnąco, natomiast drugiej malejąco (ascending)

In [76]:
mcd.sort_values(by=["Category", "Item"], ascending=[True, False]).head(20)

Category                                       Item    Serving Size  \
43   Beef & Pork                Quarter Pounder with Cheese  7.1 oz (202 g)   
45   Beef & Pork  Quarter Pounder with Bacon Habanero Ranch  8.3 oz (235 g)   
44   Beef & Pork        Quarter Pounder with Bacon & Cheese    8 oz (227 g)   
46   Beef & Pork                     Quarter Pounder Deluxe  8.6 oz (244 g)   
56   Beef & Pork                                      McRib  7.3 oz (208 g)   
52   Beef & Pork                                   McDouble  5.2 oz (147 g)   
55   Beef & Pork                            Jalapeño Double  5.6 oz (159 g)   
48   Beef & Pork                                  Hamburger   3.5 oz (98 g)   
47   Beef & Pork         Double Quarter Pounder with Cheese   10 oz (283 g)   
50   Beef & Pork                        Double Cheeseburger  5.7 oz (161 g)   
54   Beef & Pork                               Daily Double  6.7 oz (190 g)   
49   Beef & Pork                               Cheeseburger    4 oz (113 g)   
42   Beef & Pork                                    Big Mac  7.4 oz (211 g)   
53   Beef & Pork                             Bacon McDouble  5.7 oz (161 g)   
51   Beef & Pork                     Bacon Clubhouse Burger  9.5 oz (270 g)   
126    Beverages                             Sprite (Small)    16 fl oz cup   
127    Beverages                            Sprite (Medium)    21 fl oz cup   
128    Beverages                             Sprite (Large)    30 fl oz cup   
129    Beverages                             Sprite (Child)    12 fl oz cup   
133    Beverages           Minute Maid Orange Juice (Small)    12 fl oz cup   

     Calories  TotalFat  
43        520      26.0  
45        610      31.0  
44        600      29.0  
46        540      27.0  
56        500      26.0  
52        380      17.0  
55        430      23.0  
48        240       8.0  
47        750      43.0  
50        430      21.0  
54        430      22.0  
49        290      11.0  
42        530      27.0  
53        440      22.0  
51        720      40.0  
126       140       0.0  
127       200       0.0  
128       280       0.0  
129       100       0.0  
133       150       0.0

In [78]:
mcd = pd.read_csv("./data/mcdonalds.csv", usecols=["Item","Category", "Serving Size", "Calories", "TotalFat"], index_col="Item")

In [79]:
mcd.head()

Category    Serving Size  Calories  \
Item                                                                    
Egg McMuffin                      Breakfast  4.8 oz (136 g)       300   
Egg White Delight                 Breakfast  4.8 oz (135 g)       250   
Sausage McMuffin                  Breakfast  3.9 oz (111 g)       370   
Sausage McMuffin with Egg         Breakfast  5.7 oz (161 g)       450   
Sausage McMuffin with Egg Whites  Breakfast  5.7 oz (161 g)       400   

                                  TotalFat  
Item                                        
Egg McMuffin                          13.0  
Egg White Delight                      8.0  
Sausage McMuffin                      23.0  
Sausage McMuffin with Egg             28.0  
Sausage McMuffin with Egg Whites      23.0

### .sort_index()

In [80]:
mcd.sort_index().head(10)

Category       Serving Size  \
Item                                                                           
1% Low Fat Milk Jug                             Beverages  1 carton (236 ml)   
Apple Slices                               Snacks & Sides      1.2 oz (34 g)   
Bacon Buffalo Ranch McChicken              Chicken & Fish     5.7 oz (161 g)   
Bacon Cheddar McChicken                    Chicken & Fish       6 oz (171 g)   
Bacon Clubhouse Burger                        Beef & Pork     9.5 oz (270 g)   
Bacon Clubhouse Crispy Chicken Sandwich    Chicken & Fish      10 oz (284 g)   
Bacon Clubhouse Grilled Chicken Sandwich   Chicken & Fish     9.5 oz (270 g)   
Bacon McDouble                                Beef & Pork     5.7 oz (161 g)   
Bacon, Egg & Cheese Bagel                       Breakfast     6.9 oz (197 g)   
Bacon, Egg & Cheese Bagel with Egg Whites       Breakfast     7.1 oz (201 g)   

                                           Calories  TotalFat  
Item                                                           
1% Low Fat Milk Jug                             100       2.5  
Apple Slices                                     15       0.0  
Bacon Buffalo Ranch McChicken                   430      21.0  
Bacon Cheddar McChicken                         480      24.0  
Bacon Clubhouse Burger                          720      40.0  
Bacon Clubhouse Crispy Chicken Sandwich         750      38.0  
Bacon Clubhouse Grilled Chicken Sandwich        590      25.0  
Bacon McDouble                                  440      22.0  
Bacon, Egg & Cheese Bagel                       620      31.0  
Bacon, Egg & Cheese Bagel with Egg Whites       570      25.0

In [81]:
mcd.sort_index(ascending=False).head(10)

Category    Serving Size  Calories  \
Item                                                                      
Vanilla Shake (Small)      Smoothies & Shakes    12 fl oz cup       530   
Vanilla Shake (Medium)     Smoothies & Shakes    16 fl oz cup       660   
Vanilla Shake (Large)      Smoothies & Shakes    22 fl oz cup       820   
Sweet Tea (Small)                Coffee & Tea    16 fl oz cup       150   
Sweet Tea (Medium)               Coffee & Tea    21 fl oz cup       180   
Sweet Tea (Large)                Coffee & Tea    30 fl oz cup       220   
Sweet Tea (Child)                Coffee & Tea    12 fl oz cup       110   
Strawberry Sundae                    Desserts  6.3 oz (178 g)       280   
Strawberry Shake (Small)   Smoothies & Shakes    12 fl oz cup       550   
Strawberry Shake (Medium)  Smoothies & Shakes    16 fl oz cup       690   

                           TotalFat  
Item                                 
Vanilla Shake (Small)          15.0  
Vanilla Shake (Medium)         19.0  
Vanilla Shake (Large)          23.0  
Sweet Tea (Small)               0.0  
Sweet Tea (Medium)              0.0  
Sweet Tea (Large)               0.0  
Sweet Tea (Child)               0.0  
Strawberry Sundae               6.0  
Strawberry Shake (Small)       16.0  
Strawberry Shake (Medium)      20.0

# Ćwiczenie
7. Sortowanie data frame

In [82]:
import pandas as pd
import numpy as np

In [95]:
fuel = pd.read_csv("./data/fuel.csv", usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'], index_col="Vehicle ID")

In [84]:
fuel.head()

Year        Make               Model                        Class  \
Vehicle ID                                                                      
26587       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
27705       1984  Alfa Romeo           GT V6 2.5             Minicompact Cars   
26561       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27681       1984  Alfa Romeo  Spider Veloce 2000                  Two Seaters   
27550       1984  AM General   DJ Po Vehicle 2WD  Special Purpose Vehicle 2WD   

           Fuel Type  Combined MPG (FT1)  
Vehicle ID                                
26587        Regular                20.0  
27705        Regular                20.0  
26561        Regular                21.0  
27681        Regular                21.0  
27550        Regular                17.0

In [87]:
fuel.loc[27681, 'Combined MPG (FT1)'] = np. NaN

In [88]:
fuel.head()

Year        Make               Model  \
Vehicle ID                                           
26587       1984.0  Alfa Romeo           GT V6 2.5   
27705       1984.0  Alfa Romeo           GT V6 2.5   
26561       1984.0  Alfa Romeo  Spider Veloce 2000   
27681       1984.0  Alfa Romeo  Spider Veloce 2000   
27550       1984.0  AM General   DJ Po Vehicle 2WD   

                                  Class Fuel Type  Combined MPG (FT1)  
Vehicle ID                                                             
26587                  Minicompact Cars   Regular                20.0  
27705                  Minicompact Cars   Regular                20.0  
26561                       Two Seaters   Regular                21.0  
27681                       Two Seaters   Regular                 NaN  
27550       Special Purpose Vehicle 2WD   Regular                17.0

In [90]:
fuel.sort_values(by=['Make', 'Model']).head(10)

Year              Make                Model  \
Vehicle ID                                                  
27550       1984.0        AM General    DJ Po Vehicle 2WD   
28426       1984.0        AM General    DJ Po Vehicle 2WD   
27549       1984.0        AM General     FJ8c Post Office   
28425       1984.0        AM General     FJ8c Post Office   
1032        1985.0        AM General  Post Office DJ5 2WD   
1033        1985.0        AM General  Post Office DJ8 2WD   
3347        1987.0  ASC Incorporated                  GNX   
13309       1997.0             Acura          2.2CL/3.0CL   
13311       1997.0             Acura          2.2CL/3.0CL   
13310       1997.0             Acura          2.2CL/3.0CL   

                                  Class Fuel Type  Combined MPG (FT1)  
Vehicle ID                                                             
27550       Special Purpose Vehicle 2WD   Regular                17.0  
28426       Special Purpose Vehicle 2WD   Regular                17.0  
27549       Special Purpose Vehicle 2WD   Regular                13.0  
28425       Special Purpose Vehicle 2WD   Regular                13.0  
1032        Special Purpose Vehicle 2WD   Regular                16.0  
1033        Special Purpose Vehicle 2WD   Regular                13.0  
3347                       Midsize Cars   Premium                16.0  
13309                   Subcompact Cars   Regular                22.0  
13311                   Subcompact Cars   Regular                20.0  
13310                   Subcompact Cars   Regular                24.0

In [91]:
fuel.sort_values(by=['Combined MPG (FT1)'], ascending=False).head(10)

Year        Make                            Model  \
Vehicle ID                                                        
31673       2012.0  Mitsubishi                           i-MiEV   
32278       2012.0        Ford                   Focus Electric   
32276       2011.0         BMW                         Active E   
30979       2011.0      Nissan                             Leaf   
30978       2008.0        MINI                            MiniE   
31065       2011.0       smart      fortwo electric drive coupe   
31064       2011.0       smart  fortwo electric drive cabriolet   
30968       1999.0         GMC                              EV1   
16423       2000.0      Nissan                         Altra EV   
18290       2002.0      Toyota                          RAV4 EV   

                                  Class    Fuel Type  Combined MPG (FT1)  
Vehicle ID                                                                
31673                   Subcompact Cars  Electricity               112.0  
32278                      Compact Cars  Electricity               105.0  
32276                   Subcompact Cars  Electricity               102.0  
30979                      Midsize Cars  Electricity                99.0  
30978                  Minicompact Cars  Electricity                98.0  
31065                       Two Seaters  Electricity                87.0  
31064                       Two Seaters  Electricity                87.0  
30968                       Two Seaters  Electricity                85.0  
16423            Midsize Station Wagons  Electricity                85.0  
18290       Sport Utility Vehicle - 2WD  Electricity                78.0

In [93]:
fuel.sort_values(by=['Make', 'Combined MPG (FT1)'], ascending=[True, False]).head(10)

Year              Make                Model  \
Vehicle ID                                                  
27550       1984.0        AM General    DJ Po Vehicle 2WD   
28426       1984.0        AM General    DJ Po Vehicle 2WD   
1032        1985.0        AM General  Post Office DJ5 2WD   
27549       1984.0        AM General     FJ8c Post Office   
28425       1984.0        AM General     FJ8c Post Office   
1033        1985.0        AM General  Post Office DJ8 2WD   
3347        1987.0  ASC Incorporated                  GNX   
17406       2002.0             Acura                  RSX   
18390       2003.0             Acura                  RSX   
19445       2004.0             Acura                  RSX   

                                  Class Fuel Type  Combined MPG (FT1)  
Vehicle ID                                                             
27550       Special Purpose Vehicle 2WD   Regular                17.0  
28426       Special Purpose Vehicle 2WD   Regular                17.0  
1032        Special Purpose Vehicle 2WD   Regular                16.0  
27549       Special Purpose Vehicle 2WD   Regular                13.0  
28425       Special Purpose Vehicle 2WD   Regular                13.0  
1033        Special Purpose Vehicle 2WD   Regular                13.0  
3347                       Midsize Cars   Premium                16.0  
17406                   Subcompact Cars   Regular                26.0  
18390                   Subcompact Cars   Regular                26.0  
19445                   Subcompact Cars   Regular                26.0

In [96]:
fuel.sort_values(by="Combined MPG (FT1)", na_position="first").head(10)

Year         Make         Model         Class Fuel Type  \
Vehicle ID                                                            
32106       2012    Mitsubish           NaN           NaN       NaN   
1711        1986  Lamborghini      Countach   Two Seaters   Premium   
2914        1987  Lamborghini      Countach   Two Seaters   Premium   
4141        1988  Lamborghini      Countach   Two Seaters   Premium   
6413        1990  Lamborghini      Countach   Two Seaters   Premium   
5267        1989  Lamborghini      Countach   Two Seaters   Premium   
8594        1992       Vector            W8   Two Seaters   Premium   
379         1985  Rolls-Royce      Camargue  Compact Cars   Regular   
27005       1984     Maserati  Quattroporte  Midsize Cars   Regular   
28062       1984     Maserati  Quattroporte  Midsize Cars   Regular   

            Combined MPG (FT1)  
Vehicle ID                      
32106                      NaN  
1711                       7.0  
2914                       7.0  
4141                       7.0  
6413                       7.0  
5267                       7.0  
8594                       8.0  
379                        8.0  
27005                      8.0  
28062                      8.0

In [97]:
fuel.sort_index().head(10)

Year        Make               Model        Class Fuel Type  \
Vehicle ID                                                                
1           1985  Alfa Romeo  Spider Veloce 2000  Two Seaters   Regular   
2           1985     Bertone                X1/9  Two Seaters   Regular   
3           1985   Chevrolet            Corvette  Two Seaters   Regular   
4           1985   Chevrolet            Corvette  Two Seaters   Regular   
5           1985      Nissan               300ZX  Two Seaters   Regular   
6           1985      Nissan               300ZX  Two Seaters   Regular   
7           1985      Nissan               300ZX  Two Seaters   Regular   
8           1985      Nissan               300ZX  Two Seaters   Regular   
9           1985      Nissan               300ZX  Two Seaters   Regular   
10          1985     Ferrari          Testarossa  Two Seaters   Regular   

            Combined MPG (FT1)  
Vehicle ID                      
1                         21.0  
2                         22.0  
3                         17.0  
4                         17.0  
5                         16.0  
6                         17.0  
7                         17.0  
8                         19.0  
9                         18.0  
10                        11.0

# Kontrola typów 


In [98]:
mcd = pd.read_csv("./data/mcdonalds.csv", usecols=["Item","Category", "Serving Size", "Calories", "TotalFat"])

In [99]:
mcd.head()

Category                              Item    Serving Size  Calories  \
0  Breakfast                      Egg McMuffin  4.8 oz (136 g)       300   
1  Breakfast                 Egg White Delight  4.8 oz (135 g)       250   
2  Breakfast                  Sausage McMuffin  3.9 oz (111 g)       370   
3  Breakfast         Sausage McMuffin with Egg  5.7 oz (161 g)       450   
4  Breakfast  Sausage McMuffin with Egg Whites  5.7 oz (161 g)       400   

   TotalFat  
0      13.0  
1       8.0  
2      23.0  
3      28.0  
4      23.0

sprawdzamy jakie typy danych mamy w data frame

In [100]:
mcd.dtypes

Category         object
Item             object
Serving Size     object
Calories          int64
TotalFat        float64
dtype: object

In [101]:
mcd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Category      260 non-null    object 
 1   Item          260 non-null    object 
 2   Serving Size  260 non-null    object 
 3   Calories      260 non-null    int64  
 4   TotalFat      260 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 10.3+ KB


uzyskiwanie dokładnej wartości pamięci zużywanej przez data frame

In [102]:
mcd.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Category      260 non-null    object 
 1   Item          260 non-null    object 
 2   Serving Size  260 non-null    object 
 3   Calories      260 non-null    int64  
 4   TotalFat      260 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 61.7 KB


### Zmiana typu .astype()
np. .astype('int') 
<br> nie możemy zmienić typu kolumny na int jeżeli posiada wartość NaN
<br> wtedy musimy wykorzystać metodę drop, aby usunąć te wiersze, które mają wartość NaN lub metodę fillna i zmienić wartości na wartości liczbowe
<br> metoda .astype() nie posiada argumentu inplace, dlatego jeśli chcemy zachować zmianę typu to musimy przypisać do zmiennej o tej samej nazwie 

In [103]:
mcd['Calories'] = mcd['Calories'].astype('float')

In [105]:
mcd.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Category      260 non-null    object 
 1   Item          260 non-null    object 
 2   Serving Size  260 non-null    object 
 3   Calories      260 non-null    float64
 4   TotalFat      260 non-null    float64
dtypes: float64(2), object(3)
memory usage: 61.7 KB


In [106]:
mcd['Calories'] = mcd['Calories'].astype('object')

In [107]:
mcd.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Category      260 non-null    object 
 1   Item          260 non-null    object 
 2   Serving Size  260 non-null    object 
 3   Calories      260 non-null    object 
 4   TotalFat      260 non-null    float64
dtypes: float64(1), object(4)
memory usage: 67.8 KB


In [108]:
mcd['Calories'] = mcd['Calories'].astype('int')

In [109]:
mcd.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Category      260 non-null    object 
 1   Item          260 non-null    object 
 2   Serving Size  260 non-null    object 
 3   Calories      260 non-null    int32  
 4   TotalFat      260 non-null    float64
dtypes: float64(1), int32(1), object(3)
memory usage: 60.6 KB


##### typy object zajmują najwięcej pamięci, natomiast int najmniej
<br><br>
### Optymalizacja 
<br> w columnie Category wiele wartości się powtarza. Chcemy sprawić, aby zajmowały mniej pamięci.

In [111]:
mcd['Category'].value_counts()

Coffee & Tea          95
Breakfast             42
Smoothies & Shakes    28
Chicken & Fish        27
Beverages             27
Beef & Pork           15
Snacks & Sides        13
Desserts               7
Salads                 6
Name: Category, dtype: int64

In [113]:
mcd['Category'] = mcd['Category'].astype('category')      # typ category nie ma nic wspólnego z nazwą kolumny Category

In [115]:
mcd.head()

Category                              Item    Serving Size  Calories  \
0  Breakfast                      Egg McMuffin  4.8 oz (136 g)       300   
1  Breakfast                 Egg White Delight  4.8 oz (135 g)       250   
2  Breakfast                  Sausage McMuffin  3.9 oz (111 g)       370   
3  Breakfast         Sausage McMuffin with Egg  5.7 oz (161 g)       450   
4  Breakfast  Sausage McMuffin with Egg Whites  5.7 oz (161 g)       400   

   TotalFat  
0      13.0  
1       8.0  
2      23.0  
3      28.0  
4      23.0

nic w data frame się nie zminiło, ale... 

In [116]:
mcd.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   Category      260 non-null    category
 1   Item          260 non-null    object  
 2   Serving Size  260 non-null    object  
 3   Calories      260 non-null    int32   
 4   TotalFat      260 non-null    float64 
dtypes: category(1), float64(1), int32(1), object(2)
memory usage: 44.3 KB


pamięc zużywana znacznie zmalała (44.3 KB, a było 60.6 KB)

In [117]:
mcd['Serving Size'].value_counts()

16 fl oz cup       45
12 fl oz cup       38
22 fl oz cup       20
20 fl oz cup       16
30 fl oz cup        7
                   ..
8 oz (227 g)        1
7.4 oz (211 g)      1
4 oz (114 g)        1
2 oz (56 g)         1
14.2 oz (403 g)     1
Name: Serving Size, Length: 107, dtype: int64

w kolumnie Serving Size też wiele danych się powtarza, więc można spróbować zoptymalizować nasz data frame

In [118]:
mcd['Serving Size'] = mcd['Serving Size'].astype('category')

In [121]:
mcd.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   Category      260 non-null    category
 1   Item          260 non-null    object  
 2   Serving Size  260 non-null    category
 3   Calories      260 non-null    int32   
 4   TotalFat      260 non-null    float64 
dtypes: category(2), float64(1), int32(1), object(1)
memory usage: 38.3 KB


i znowu zmniejszyliśmy ilość zużywanej pamięci (38.3 KB)

# Ćwiczenie 
8. Kontrola i optymalizacja typów danych

In [122]:
import pandas as pd 
import numpy as np

In [144]:
fuel = pd.read_csv("./data/fuel.csv", usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'])

In [145]:
fuel.head(10)

Vehicle ID  Year                         Make               Model  \
0       26587  1984                   Alfa Romeo           GT V6 2.5   
1       27705  1984                   Alfa Romeo           GT V6 2.5   
2       26561  1984                   Alfa Romeo  Spider Veloce 2000   
3       27681  1984                   Alfa Romeo  Spider Veloce 2000   
4       27550  1984                   AM General   DJ Po Vehicle 2WD   
5       28426  1984                   AM General   DJ Po Vehicle 2WD   
6       27549  1984                   AM General    FJ8c Post Office   
7       28425  1984                   AM General    FJ8c Post Office   
8       27593  1984  American Motors Corporation           Eagle 4WD   
9       28455  1984  American Motors Corporation           Eagle 4WD   

                         Class Fuel Type  Combined MPG (FT1)  
0             Minicompact Cars   Regular                20.0  
1             Minicompact Cars   Regular                20.0  
2                  Two Seaters   Regular                21.0  
3                  Two Seaters   Regular                21.0  
4  Special Purpose Vehicle 2WD   Regular                17.0  
5  Special Purpose Vehicle 2WD   Regular                17.0  
6  Special Purpose Vehicle 2WD   Regular                13.0  
7  Special Purpose Vehicle 2WD   Regular                13.0  
8  Special Purpose Vehicle 4WD   Regular                17.0  
9  Special Purpose Vehicle 4WD   Regular                17.0

In [146]:
fuel.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31684 entries, 0 to 31683
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Vehicle ID          31684 non-null  int64  
 1   Year                31684 non-null  int64  
 2   Make                31684 non-null  object 
 3   Model               31683 non-null  object 
 4   Class               31683 non-null  object 
 5   Fuel Type           31683 non-null  object 
 6   Combined MPG (FT1)  31683 non-null  float64
dtypes: float64(1), int64(2), object(4)
memory usage: 8.9 MB


In [147]:
fuel['Year'] = fuel['Year'].astype('int')

In [148]:
fuel.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31684 entries, 0 to 31683
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Vehicle ID          31684 non-null  int64  
 1   Year                31684 non-null  int32  
 2   Make                31684 non-null  object 
 3   Model               31683 non-null  object 
 4   Class               31683 non-null  object 
 5   Fuel Type           31683 non-null  object 
 6   Combined MPG (FT1)  31683 non-null  float64
dtypes: float64(1), int32(1), int64(1), object(4)
memory usage: 8.8 MB


In [149]:
fuel['Make'].value_counts()

Chevrolet                 3389
Ford                      2721
Dodge                     2361
GMC                       2174
Toyota                    1599
                          ... 
General Motors               1
Panoz Auto-Development       1
Goldacre                     1
Panos                        1
Mitsubish                    1
Name: Make, Length: 128, dtype: int64

In [150]:
fuel['Make'] = fuel['Make'].astype('category')
fuel.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31684 entries, 0 to 31683
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype   
---  ------              --------------  -----   
 0   Vehicle ID          31684 non-null  int64   
 1   Year                31684 non-null  int32   
 2   Make                31684 non-null  category
 3   Model               31683 non-null  object  
 4   Class               31683 non-null  object  
 5   Fuel Type           31683 non-null  object  
 6   Combined MPG (FT1)  31683 non-null  float64 
dtypes: category(1), float64(1), int32(1), int64(1), object(3)
memory usage: 6.9 MB


In [151]:
fuel['Model'].value_counts()

F150 Pickup 2WD                 194
Truck 2WD                       187
F150 Pickup 4WD                 172
Ranger Pickup 2WD               169
Mustang                         156
                               ... 
Silver Spur II Mpw Touring L      1
Brooklands/Brklnds L              1
Vdp                               1
Pas-Typhoon                       1
Lancer AWD                        1
Name: Model, Length: 2957, dtype: int64

In [152]:
fuel['Model'] = fuel['Model'].astype('category')

In [153]:
fuel['Class'].value_counts()

Compact Cars                    4489
Subcompact Cars                 4299
Midsize Cars                    3393
Standard Pickup Trucks          2354
Sport Utility Vehicle - 4WD     2034
Sport Utility Vehicle - 2WD     1598
Special Purpose Vehicles        1455
Two Seaters                     1448
Large Cars                      1351
Small Station Wagons            1275
Vans                            1141
Standard Pickup Trucks 2WD      1043
Minicompact Cars                 941
Standard Pickup Trucks 4WD       846
Midsize-Large Station Wagons     656
Small Pickup Trucks              538
Special Purpose Vehicle 2WD      536
Midsize Station Wagons           492
Vans, Cargo Type                 397
Small Pickup Trucks 2WD          365
Special Purpose Vehicle 4WD      287
Minivan - 2WD                    278
Vans, Passenger Type             253
Small Pickup Trucks 4WD          162
Minivan - 4WD                     41
Standard Pickup Trucks/2wd         4
Vans Passenger                     2
S

In [154]:
fuel['Class'] = fuel['Class'].astype('category')


In [155]:
fuel['Fuel Type'].value_counts()

Regular                       22439
Premium                        7375
Diesel                          936
Gasoline or E85                 767
CNG                              55
Electricity                      33
Premium or E85                   33
Gasoline or natural gas          18
Midgrade                         16
Gasoline or propane               8
Premium Gas or Electricity        3
Name: Fuel Type, dtype: int64

In [156]:
fuel['Fuel Type'] = fuel['Fuel Type'].astype('category')

In [157]:
fuel['Combined MPG (FT1)'] = fuel['Combined MPG (FT1)'].astype('float')

In [158]:
fuel.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31684 entries, 0 to 31683
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype   
---  ------              --------------  -----   
 0   Vehicle ID          31684 non-null  int64   
 1   Year                31684 non-null  int32   
 2   Make                31684 non-null  category
 3   Model               31683 non-null  category
 4   Class               31683 non-null  category
 5   Fuel Type           31683 non-null  category
 6   Combined MPG (FT1)  31683 non-null  float64 
dtypes: category(4), float64(1), int32(1), int64(1)
memory usage: 1.1 MB


# Ranking
sortowanie i przypisanie miejsc w rankingu danym 

In [159]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [160]:
mcd = pd.read_csv("./data/mcdonalds.csv", usecols=["Item","Category", "Serving Size", "Calories", "TotalFat"])

In [161]:
mcd.head(10)

Category                                               Item  \
0  Breakfast                                       Egg McMuffin   
1  Breakfast                                  Egg White Delight   
2  Breakfast                                   Sausage McMuffin   
3  Breakfast                          Sausage McMuffin with Egg   
4  Breakfast                   Sausage McMuffin with Egg Whites   
5  Breakfast                               Steak & Egg McMuffin   
6  Breakfast      Bacon, Egg & Cheese Biscuit (Regular Biscuit)   
7  Breakfast        Bacon, Egg & Cheese Biscuit (Large Biscuit)   
8  Breakfast  Bacon, Egg & Cheese Biscuit with Egg Whites (R...   
9  Breakfast  Bacon, Egg & Cheese Biscuit with Egg Whites (L...   

     Serving Size  Calories  TotalFat  
0  4.8 oz (136 g)       300      13.0  
1  4.8 oz (135 g)       250       8.0  
2  3.9 oz (111 g)       370      23.0  
3  5.7 oz (161 g)       450      28.0  
4  5.7 oz (161 g)       400      23.0  
5  6.5 oz (185 g)       430      23.0  
6  5.3 oz (150 g)       460      26.0  
7  5.8 oz (164 g)       520      30.0  
8  5.4 oz (153 g)       410      20.0  
9  5.9 oz (167 g)       470      25.0

Tworzymy ranking najbardziej kalorycznych dań z McD 
### .rank()

In [162]:
mcd['Calories'].rank().head(10)

0    115.0
1     82.5
2    146.0
3    178.5
4    156.0
5    168.5
6    184.0
7    205.0
8    159.5
9    188.0
Name: Calories, dtype: float64

dodajemy kolumne CaloriesRank do dataFrame

In [163]:
mcd['CaloriesRank'] = mcd['Calories'].rank()

In [164]:
mcd.head()

Category                              Item    Serving Size  Calories  \
0  Breakfast                      Egg McMuffin  4.8 oz (136 g)       300   
1  Breakfast                 Egg White Delight  4.8 oz (135 g)       250   
2  Breakfast                  Sausage McMuffin  3.9 oz (111 g)       370   
3  Breakfast         Sausage McMuffin with Egg  5.7 oz (161 g)       450   
4  Breakfast  Sausage McMuffin with Egg Whites  5.7 oz (161 g)       400   

   TotalFat  CaloriesRank  
0      13.0         115.0  
1       8.0          82.5  
2      23.0         146.0  
3      28.0         178.5  
4      23.0         156.0

sortujemy dane po ilości kalorii 

In [167]:
mcd.sort_values(by='Calories').head(25)

Category                                               Item  \
125       Beverages                             Diet Dr Pepper (Child)   
138    Coffee & Tea                                  Iced Tea (Medium)   
137    Coffee & Tea                                   Iced Tea (Small)   
136       Beverages                                Dasani Water Bottle   
145    Coffee & Tea                                     Coffee (Small)   
147    Coffee & Tea                                     Coffee (Large)   
124       Beverages                             Diet Dr Pepper (Large)   
139    Coffee & Tea                                   Iced Tea (Large)   
122       Beverages                             Diet Dr Pepper (Small)   
123       Beverages                            Diet Dr Pepper (Medium)   
117       Beverages                                  Diet Coke (Child)   
116       Beverages                                  Diet Coke (Large)   
115       Beverages                                 Diet Coke (Medium)   
114       Beverages                                  Diet Coke (Small)   
146    Coffee & Tea                                    Coffee (Medium)   
140    Coffee & Tea                                   Iced Tea (Child)   
101  Snacks & Sides                                       Apple Slices   
100  Snacks & Sides                                         Side Salad   
106        Desserts                                Kids Ice Cream Cone   
132       Beverages                   Minute Maid 100% Apple Juice Box   
208    Coffee & Tea  Iced Coffee with Sugar Free French Vanilla Syr...   
129       Beverages                                     Sprite (Child)   
121       Beverages                                  Dr Pepper (Child)   
130       Beverages                                1% Low Fat Milk Jug   
163    Coffee & Tea                               Nonfat Latte (Small)   

          Serving Size  Calories  TotalFat  CaloriesRank  
125       12 fl oz cup         0       0.0           8.5  
138       21 fl oz cup         0       0.0           8.5  
137       16 fl oz cup         0       0.0           8.5  
136         16.9 fl oz         0       0.0           8.5  
145       12 fl oz cup         0       0.0           8.5  
147       16 fl oz cup         0       0.0           8.5  
124       30 fl oz cup         0       0.0           8.5  
139       30 fl oz cup         0       0.0           8.5  
122       16 fl oz cup         0       0.0           8.5  
123       21 fl oz cup         0       0.0           8.5  
117       12 fl oz cup         0       0.0           8.5  
116       30 fl oz cup         0       0.0           8.5  
115       21 fl oz cup         0       0.0           8.5  
114       16 fl oz cup         0       0.0           8.5  
146       16 fl oz cup         0       0.0           8.5  
140       12 fl oz cup         0       0.0           8.5  
101      1.2 oz (34 g)        15       0.0          17.0  
100      3.1 oz (87 g)        20       0.0          18.0  
106        1 oz (29 g)        45       1.5          19.0  
132   6 fl oz (177 ml)        80       0.0          20.5  
208       16 fl oz cup        80       4.5          20.5  
129       12 fl oz cup       100       0.0          24.0  
121       12 fl oz cup       100       0.0          24.0  
130  1 carton (236 ml)       100       2.5          24.0  
163       12 fl oz cup       100       0.0          24.0

#### .rank(axis=0, method='average', numeric_only=None, na_option='keep', ascending=True, pct=False)
<br> axis = 0 - wiersz, axis = 1 - kolumna
<br> method='average' - dlatego mamy wyniki np 8,5, ponieważ bierze średnią z rankingów jakie powinny być przydzielone jeśli są na tej samej pozycji
<br> ascending = True(rosnące), False(malejące)

In [171]:
mcd['CaloriesRank'] = mcd['Calories'].rank(ascending=False,)
mcd.sort_values(by='Calories', ascending=False).head(20)

Category                                               Item  \
82       Chicken & Fish                       Chicken McNuggets (40 piece)   
32            Breakfast        Big Breakfast with Hotcakes (Large Biscuit)   
31            Breakfast      Big Breakfast with Hotcakes (Regular Biscuit)   
34            Breakfast  Big Breakfast with Hotcakes and Egg Whites (La...   
33            Breakfast  Big Breakfast with Hotcakes and Egg Whites (Re...   
81       Chicken & Fish                       Chicken McNuggets (20 piece)   
253  Smoothies & Shakes               McFlurry with M&M’s Candies (Medium)   
249  Smoothies & Shakes                            Chocolate Shake (Large)   
246  Smoothies & Shakes                           Strawberry Shake (Large)   
251  Smoothies & Shakes                             Shamrock Shake (Large)   
243  Smoothies & Shakes                              Vanilla Shake (Large)   
258  Smoothies & Shakes  McFlurry with Reese's Peanut Butter Cups (Medium)   
28            Breakfast                      Big Breakfast (Large Biscuit)   
231        Coffee & Tea                      Frappé Chocolate Chip (Large)   
47          Beef & Pork                 Double Quarter Pounder with Cheese   
63       Chicken & Fish            Bacon Clubhouse Crispy Chicken Sandwich   
27            Breakfast                    Big Breakfast (Regular Biscuit)   
51          Beef & Pork                             Bacon Clubhouse Burger   
248  Smoothies & Shakes                           Chocolate Shake (Medium)   
30            Breakfast      Big Breakfast with Egg Whites (Large Biscuit)   

        Serving Size  Calories  TotalFat  CaloriesRank  
82   22.8 oz (646 g)      1880     118.0           1.0  
32   15.3 oz (434 g)      1150      60.0           2.0  
31   14.8 oz (420 g)      1090      56.0           3.0  
34   15.4 oz (437 g)      1050      50.0           4.0  
33   14.9 oz (423 g)       990      46.0           5.0  
81   11.4 oz (323 g)       940      59.0           6.0  
253  16.2 oz (460 g)       930      33.0           7.0  
249     22 fl oz cup       850      23.0           8.5  
246     22 fl oz cup       850      24.0           8.5  
251     22 fl oz cup       820      23.0          10.5  
243     22 fl oz cup       820      23.0          10.5  
258  14.2 oz (403 g)       810      32.0          12.0  
28     10 oz (283 g)       800      52.0          13.0  
231     22 fl oz cup       760      31.0          14.0  
47     10 oz (283 g)       750      43.0          15.5  
63     10 oz (284 g)       750      38.0          15.5  
27    9.5 oz (269 g)       740      48.0          17.0  
51    9.5 oz (270 g)       720      40.0          18.0  
248     16 fl oz cup       700      20.0          19.0  
30   10.1 oz (286 g)       690      41.0          21.0

Chcemy znaleźć 3 najbardziej kaloryczne w data frame. Robimy na 2 sposoby 

In [172]:
mcd.sort_values(by='Calories', ascending=False, inplace=True)

In [173]:
mcd.head(3)

Category                                           Item  \
82  Chicken & Fish                   Chicken McNuggets (40 piece)   
32       Breakfast    Big Breakfast with Hotcakes (Large Biscuit)   
31       Breakfast  Big Breakfast with Hotcakes (Regular Biscuit)   

       Serving Size  Calories  TotalFat  CaloriesRank  
82  22.8 oz (646 g)      1880     118.0           1.0  
32  15.3 oz (434 g)      1150      60.0           2.0  
31  14.8 oz (420 g)      1090      56.0           3.0

### .nlargest (n=x, columns='x')

In [174]:
mcd.nlargest(n=3, columns='Calories')

Category                                           Item  \
82  Chicken & Fish                   Chicken McNuggets (40 piece)   
32       Breakfast    Big Breakfast with Hotcakes (Large Biscuit)   
31       Breakfast  Big Breakfast with Hotcakes (Regular Biscuit)   

       Serving Size  Calories  TotalFat  CaloriesRank  
82  22.8 oz (646 g)      1880     118.0           1.0  
32  15.3 oz (434 g)      1150      60.0           2.0  
31  14.8 oz (420 g)      1090      56.0           3.0

najmniej kaloryczne (jest już na stałe posortowane od największej)

In [175]:
mcd.tail(3)

Category                Item  Serving Size  Calories  TotalFat  \
115     Beverages  Diet Coke (Medium)  21 fl oz cup         0       0.0   
114     Beverages   Diet Coke (Small)  16 fl oz cup         0       0.0   
146  Coffee & Tea     Coffee (Medium)  16 fl oz cup         0       0.0   

     CaloriesRank  
115         252.5  
114         252.5  
146         252.5

### .nsmallest(n=x, columns='x')

In [177]:
mcd.nsmallest(n=3, columns='Calories')

Category              Item  Serving Size  Calories  TotalFat  \
145  Coffee & Tea    Coffee (Small)  12 fl oz cup         0       0.0   
140  Coffee & Tea  Iced Tea (Child)  12 fl oz cup         0       0.0   
139  Coffee & Tea  Iced Tea (Large)  30 fl oz cup         0       0.0   

     CaloriesRank  
145         252.5  
140         252.5  
139         252.5

# Ćwiczenie 
9. Ranking

In [178]:
import pandas as pd
import numpy as np

In [207]:
fortune = pd.read_csv('./data/Fortune_500_2017.csv', usecols=['Rank', 'Title', 'Employees', 'Profits', 'Assets'], index_col='Rank')

In [208]:
fortune.head(10)

Title  Employees  Profits  Assets
Rank                                                
1                Walmart    2300000  13643.0  198825
2     Berkshire Hathaway     367700  24074.0  620854
3                  Apple     116000  45687.0  321686
4            Exxon Mobil      72700   7840.0  330314
5               McKesson      68000   2258.0   56563
6     UnitedHealth Group     230000   7017.0  122810
7             CVS Health     204000   5317.0   94462
8         General Motors     225000   9427.0  221690
9                   AT&T     268540  12976.0  403821
10            Ford Motor     201000   4596.0  237951

In [209]:
fortune['Employees'].rank(ascending=False).head(10)

Rank
1       1.0
2       7.0
3      57.0
4      94.0
5     104.5
6      23.0
7      30.0
8      25.0
9      16.0
10     32.0
Name: Employees, dtype: float64

In [219]:
fortune['RankByEmployees'] = fortune['Employees'].rank(ascending=False)

In [211]:
fortune.head(10)

Title  Employees  Profits  Assets  RankByEmployees
Rank                                                                 
1                Walmart    2300000  13643.0  198825              1.0
2     Berkshire Hathaway     367700  24074.0  620854              7.0
3                  Apple     116000  45687.0  321686             57.0
4            Exxon Mobil      72700   7840.0  330314             94.0
5               McKesson      68000   2258.0   56563            104.5
6     UnitedHealth Group     230000   7017.0  122810             23.0
7             CVS Health     204000   5317.0   94462             30.0
8         General Motors     225000   9427.0  221690             25.0
9                   AT&T     268540  12976.0  403821             16.0
10            Ford Motor     201000   4596.0  237951             32.0

In [212]:
fortune['Profits'].rank(ascending=False).head(10)

Rank
1      11.0
2       3.0
3       1.0
4      27.0
5     102.0
6      33.0
7      44.0
8      21.0
9      14.0
10     52.0
Name: Profits, dtype: float64

In [220]:
fortune['RankByProfits'] = fortune['Profits'].rank(ascending=False)

In [214]:
fortune.head(10)

Title  Employees  Profits  Assets  RankByEmployees  \
Rank                                                                    
1                Walmart    2300000  13643.0  198825              1.0   
2     Berkshire Hathaway     367700  24074.0  620854              7.0   
3                  Apple     116000  45687.0  321686             57.0   
4            Exxon Mobil      72700   7840.0  330314             94.0   
5               McKesson      68000   2258.0   56563            104.5   
6     UnitedHealth Group     230000   7017.0  122810             23.0   
7             CVS Health     204000   5317.0   94462             30.0   
8         General Motors     225000   9427.0  221690             25.0   
9                   AT&T     268540  12976.0  403821             16.0   
10            Ford Motor     201000   4596.0  237951             32.0   

      RankByProfits  
Rank                 
1              11.0  
2               3.0  
3               1.0  
4              27.0  
5             102.0  
6              33.0  
7              44.0  
8              21.0  
9              14.0  
10             52.0

In [221]:
fortune.nlargest(n=3, columns='Assets')

Title  Employees  Profits   Assets  RankByEmployees  \
Rank                                                                        
20               Fannie Mae       7000  12313.0  3287968            446.5   
21        J.P. Morgan Chase     243355  24733.0  2490972             20.0   
26    Bank of America Corp.     208024  17906.0  2187702             29.0   

      RankByProfits  
Rank                 
20             15.0  
21              2.0  
26              6.0

In [222]:
fortune.sort_values(by='Assets', ascending=False, inplace=True)

In [223]:
fortune.head(10)

Title  Employees  Profits   Assets  RankByEmployees  \
Rank                                                                        
20               Fannie Mae       7000  12313.0  3287968            446.5   
21        J.P. Morgan Chase     243355  24733.0  2490972             20.0   
26    Bank of America Corp.     208024  17906.0  2187702             29.0   
39              Freddie Mac       5982   7815.0  2023376            458.0   
25              Wells Fargo     269100  21938.0  1930115             15.0   
30                Citigroup     219000  14912.0  1792077             26.0   
42                  MetLife      58000    800.0   898764            123.0   
78      Goldman Sachs Group      34400   7398.0   860165            202.0   
76           Morgan Stanley      55311   5979.0   814949            131.0   
48     Prudential Financial      49739   4368.0   783962            152.0   

      RankByProfits  
Rank                 
20             15.0  
21              2.0  
26              6.0  
39             28.0  
25              4.0  
30              9.0  
42            228.0  
78             30.0  
76             39.0  
48             55.0

# Filtrowanie danych w data frame
filtrowanie danych według pewnych kryteriów 


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [19]:
mcd = pd.read_csv("./data/mcdonalds.csv", usecols=["Item","Category", "Serving Size", "Calories", "TotalFat"])

In [3]:
mcd.head()

Category                              Item    Serving Size  Calories  \
0  Breakfast                      Egg McMuffin  4.8 oz (136 g)       300   
1  Breakfast                 Egg White Delight  4.8 oz (135 g)       250   
2  Breakfast                  Sausage McMuffin  3.9 oz (111 g)       370   
3  Breakfast         Sausage McMuffin with Egg  5.7 oz (161 g)       450   
4  Breakfast  Sausage McMuffin with Egg Whites  5.7 oz (161 g)       400   

   TotalFat  
0      13.0  
1       8.0  
2      23.0  
3      28.0  
4      23.0

gdy filtrujemy to cały argument musi znaleźćsię w (). trzymujemy wartość boolean (True or False)

In [4]:
(mcd['Calories'] >= 400).head(10)

0    False
1    False
2    False
3     True
4     True
5     True
6     True
7     True
8     True
9     True
Name: Calories, dtype: bool

In [6]:
(mcd['TotalFat']<=20).head(10)

0     True
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8     True
9    False
Name: TotalFat, dtype: bool

Żeby wykorzystać filtrowanie w naszym data frame i otrzymać normalne wartości zamiast boolean musimy przypisać filtrowanie do zmiennej.

In [7]:
caloriesGreaterEqual400 = mcd['Calories'] >= 400

Tutaj bez ()
<br> a następnie użyć utworzoną zmienną jako argument do całego data frame

In [8]:
mcd[caloriesGreaterEqual400].head()

Category                                           Item    Serving Size  \
3  Breakfast                      Sausage McMuffin with Egg  5.7 oz (161 g)   
4  Breakfast               Sausage McMuffin with Egg Whites  5.7 oz (161 g)   
5  Breakfast                           Steak & Egg McMuffin  6.5 oz (185 g)   
6  Breakfast  Bacon, Egg & Cheese Biscuit (Regular Biscuit)  5.3 oz (150 g)   
7  Breakfast    Bacon, Egg & Cheese Biscuit (Large Biscuit)  5.8 oz (164 g)   

   Calories  TotalFat  
3       450      28.0  
4       400      23.0  
5       430      23.0  
6       460      26.0  
7       520      30.0

W taki sposób wyświetliliśmy 5 pierwszych wyrażeń, które spełniają kryteria filtrowania

In [9]:
totalFatLessEqual20 = mcd['TotalFat']<= 20

In [11]:
mcd[totalFatLessEqual20].head()

Category                                               Item  \
0   Breakfast                                       Egg McMuffin   
1   Breakfast                                  Egg White Delight   
8   Breakfast  Bacon, Egg & Cheese Biscuit with Egg Whites (R...   
16  Breakfast   Southern Style Chicken Biscuit (Regular Biscuit)   
20  Breakfast     Bacon, Egg & Cheese McGriddles with Egg Whites   

      Serving Size  Calories  TotalFat  
0   4.8 oz (136 g)       300      13.0  
1   4.8 oz (135 g)       250       8.0  
8   5.4 oz (153 g)       410      20.0  
16    5 oz (143 g)       410      20.0  
20  6.3 oz (178 g)       400      15.0

In [12]:
isBreakfast = mcd['Category'] == 'Breakfast'

#### Łączenie filtrów 

In [13]:
mcd[isBreakfast & caloriesGreaterEqual400].head()

Category                                           Item    Serving Size  \
3  Breakfast                      Sausage McMuffin with Egg  5.7 oz (161 g)   
4  Breakfast               Sausage McMuffin with Egg Whites  5.7 oz (161 g)   
5  Breakfast                           Steak & Egg McMuffin  6.5 oz (185 g)   
6  Breakfast  Bacon, Egg & Cheese Biscuit (Regular Biscuit)  5.3 oz (150 g)   
7  Breakfast    Bacon, Egg & Cheese Biscuit (Large Biscuit)  5.8 oz (164 g)   

   Calories  TotalFat  
3       450      28.0  
4       400      23.0  
5       430      23.0  
6       460      26.0  
7       520      30.0

Otrzymaliśmy dataFrame, z elementami, które są śniadaniami oraz mają kaloryczność większą niż lub równą 400

In [14]:
mcd[isBreakfast & caloriesGreaterEqual400 & totalFatLessEqual20].head()

Category                                               Item  \
8   Breakfast  Bacon, Egg & Cheese Biscuit with Egg Whites (R...   
16  Breakfast   Southern Style Chicken Biscuit (Regular Biscuit)   
20  Breakfast     Bacon, Egg & Cheese McGriddles with Egg Whites   
39  Breakfast                                     Cinnamon Melts   

      Serving Size  Calories  TotalFat  
8   5.4 oz (153 g)       410      20.0  
16    5 oz (143 g)       410      20.0  
20  6.3 oz (178 g)       400      15.0  
39    4 oz (114 g)       460      19.0

#### Znak negacji (odwrócenie kryterium fltrowania) "~"

In [15]:
mcd[~ isBreakfast].head()

Category                                       Item    Serving Size  \
42  Beef & Pork                                    Big Mac  7.4 oz (211 g)   
43  Beef & Pork                Quarter Pounder with Cheese  7.1 oz (202 g)   
44  Beef & Pork        Quarter Pounder with Bacon & Cheese    8 oz (227 g)   
45  Beef & Pork  Quarter Pounder with Bacon Habanero Ranch  8.3 oz (235 g)   
46  Beef & Pork                     Quarter Pounder Deluxe  8.6 oz (244 g)   

    Calories  TotalFat  
42       530      27.0  
43       520      26.0  
44       600      29.0  
45       610      31.0  
46       540      27.0

Wyświetliło wszystko to co nie jest śniadaniem

### Operatory filtrowania
& - i
<br> | - lub 
<br> & wykonywane jest w pierwszej kolejności, później "|". Kolejność warunków możemy zmienić używając (), tak jak w matematyce

In [19]:
mcd[caloriesGreaterEqual400 | totalFatLessEqual20 & isBreakfast].head(100)

Category                              Item    Serving Size  \
0             Breakfast                      Egg McMuffin  4.8 oz (136 g)   
1             Breakfast                 Egg White Delight  4.8 oz (135 g)   
3             Breakfast         Sausage McMuffin with Egg  5.7 oz (161 g)   
4             Breakfast  Sausage McMuffin with Egg Whites  5.7 oz (161 g)   
5             Breakfast              Steak & Egg McMuffin  6.5 oz (185 g)   
..                  ...                               ...             ...   
241  Smoothies & Shakes             Vanilla Shake (Small)    12 fl oz cup   
242  Smoothies & Shakes            Vanilla Shake (Medium)    16 fl oz cup   
243  Smoothies & Shakes             Vanilla Shake (Large)    22 fl oz cup   
244  Smoothies & Shakes          Strawberry Shake (Small)    12 fl oz cup   
245  Smoothies & Shakes         Strawberry Shake (Medium)    16 fl oz cup   

     Calories  TotalFat  
0         300      13.0  
1         250       8.0  
3         450      28.0  
4         400      23.0  
5         430      23.0  
..        ...       ...  
241       530      15.0  
242       660      19.0  
243       820      23.0  
244       550      16.0  
245       690      20.0  

[100 rows x 5 columns]

Wyświetliliśmy wszystkie dania, które są śniadaniem i ich totalFat jest mniejszy lub równy 20, a następnie wypisaliśmy wszystkie elementy, które mają kaloryczność większe lub równe 400 ( nie musiały być śniadaniem)

In [20]:
mcd[(caloriesGreaterEqual400 | totalFatLessEqual20) & isBreakfast].head(100)

Category                                               Item  \
0   Breakfast                                       Egg McMuffin   
1   Breakfast                                  Egg White Delight   
3   Breakfast                          Sausage McMuffin with Egg   
4   Breakfast                   Sausage McMuffin with Egg Whites   
5   Breakfast                               Steak & Egg McMuffin   
6   Breakfast      Bacon, Egg & Cheese Biscuit (Regular Biscuit)   
7   Breakfast        Bacon, Egg & Cheese Biscuit (Large Biscuit)   
8   Breakfast  Bacon, Egg & Cheese Biscuit with Egg Whites (R...   
9   Breakfast  Bacon, Egg & Cheese Biscuit with Egg Whites (L...   
10  Breakfast                  Sausage Biscuit (Regular Biscuit)   
11  Breakfast                    Sausage Biscuit (Large Biscuit)   
12  Breakfast         Sausage Biscuit with Egg (Regular Biscuit)   
13  Breakfast           Sausage Biscuit with Egg (Large Biscuit)   
14  Breakfast  Sausage Biscuit with Egg Whites (Regular Biscuit)   
15  Breakfast    Sausage Biscuit with Egg Whites (Large Biscuit)   
16  Breakfast   Southern Style Chicken Biscuit (Regular Biscuit)   
17  Breakfast     Southern Style Chicken Biscuit (Large Biscuit)   
18  Breakfast              Steak & Egg Biscuit (Regular Biscuit)   
19  Breakfast                     Bacon, Egg & Cheese McGriddles   
20  Breakfast     Bacon, Egg & Cheese McGriddles with Egg Whites   
21  Breakfast                                 Sausage McGriddles   
22  Breakfast                   Sausage, Egg & Cheese McGriddles   
23  Breakfast   Sausage, Egg & Cheese McGriddles with Egg Whites   
24  Breakfast                          Bacon, Egg & Cheese Bagel   
25  Breakfast          Bacon, Egg & Cheese Bagel with Egg Whites   
26  Breakfast                          Steak, Egg & Cheese Bagel   
27  Breakfast                    Big Breakfast (Regular Biscuit)   
28  Breakfast                      Big Breakfast (Large Biscuit)   
29  Breakfast    Big Breakfast with Egg Whites (Regular Biscuit)   
30  Breakfast      Big Breakfast with Egg Whites (Large Biscuit)   
31  Breakfast      Big Breakfast with Hotcakes (Regular Biscuit)   
32  Breakfast        Big Breakfast with Hotcakes (Large Biscuit)   
33  Breakfast  Big Breakfast with Hotcakes and Egg Whites (Re...   
34  Breakfast  Big Breakfast with Hotcakes and Egg Whites (La...   
35  Breakfast                                           Hotcakes   
36  Breakfast                               Hotcakes and Sausage   
37  Breakfast                                    Sausage Burrito   
38  Breakfast                                         Hash Brown   
39  Breakfast                                     Cinnamon Melts   
40  Breakfast                              Fruit & Maple Oatmeal   
41  Breakfast          Fruit & Maple Oatmeal without Brown Sugar   

       Serving Size  Calories  TotalFat  
0    4.8 oz (136 g)       300      13.0  
1    4.8 oz (135 g)       250       8.0  
3    5.7 oz (161 g)       450      28.0  
4    5.7 oz (161 g)       400      23.0  
5    6.5 oz (185 g)       430      23.0  
6    5.3 oz (150 g)       460      26.0  
7    5.8 oz (164 g)       520      30.0  
8    5.4 oz (153 g)       410      20.0  
9    5.9 oz (167 g)       470      25.0  
10   4.1 oz (117 g)       430      27.0  
11   4.6 oz (131 g)       480      31.0  
12   5.7 oz (163 g)       510      33.0  
13   6.2 oz (177 g)       570      37.0  
14   5.9 oz (167 g)       460      27.0  
15   6.4 oz (181 g)       520      32.0  
16     5 oz (143 g)       410      20.0  
17   5.5 oz (157 g)       470      24.0  
18   7.1 oz (201 g)       540      32.0  
19   6.1 oz (174 g)       460      21.0  
20   6.3 oz (178 g)       400      15.0  
21     5 oz (141 g)       420      22.0  
22   7.1 oz (201 g)       550      31.0  
23   7.2 oz (205 g)       500      26.0  
24   6.9 oz (197 g)       620      31.0  
25   7.1 oz (201 g)       570      25.0  
26   8.5 oz (241 g)       670      35.0  
27   9.5 oz (2

Tutaj natomiast dzęki nawiasowi wybraliśmy wszystkie produkty, które mają kaloryczność większą lub równą 400 oraz te które mają totalFat <= 20 i później sprawdziliśmy, czy te produkty są też śniadaniem. Dlatego wszystkie wyniki są śniadaniami.

# Ćwiczenie
10 Filtrowanie Data Frame

In [21]:
import pandas as pd
import numpy as np

In [22]:
fortune = pd.read_csv('./data/Fortune_500_2017.csv', usecols=['Rank', 'Title', 'Employees', 'Profits', 'Assets'], index_col='Rank')

In [27]:
fortune

Title  Employees  Profits  Assets
Rank                                                
1                Walmart    2300000  13643.0  198825
2     Berkshire Hathaway     367700  24074.0  620854
3                  Apple     116000  45687.0  321686
4            Exxon Mobil      72700   7840.0  330314
5               McKesson      68000   2258.0   56563
...                  ...        ...      ...     ...
496        Michaels Cos.      31000    378.2    2148
497        Toll Brothers       4200    382.1    9737
498                Yahoo       8500   -214.3   48083
499        Vistra Energy       4431   -214.3   15167
500       ABM Industries     110000     57.2    2281

[500 rows x 4 columns]

In [28]:
fortune['Employees'].rank(ascending=False).head()

Rank
1      1.0
2      7.0
3     57.0
4     94.0
5    104.5
Name: Employees, dtype: float64

In [29]:
fortune['rankByEmployees'] = fortune['Employees'].rank(ascending=False)

In [30]:
fortune.head(10)

Title  Employees  Profits  Assets  rankByEmployees
Rank                                                                 
1                Walmart    2300000  13643.0  198825              1.0
2     Berkshire Hathaway     367700  24074.0  620854              7.0
3                  Apple     116000  45687.0  321686             57.0
4            Exxon Mobil      72700   7840.0  330314             94.0
5               McKesson      68000   2258.0   56563            104.5
6     UnitedHealth Group     230000   7017.0  122810             23.0
7             CVS Health     204000   5317.0   94462             30.0
8         General Motors     225000   9427.0  221690             25.0
9                   AT&T     268540  12976.0  403821             16.0
10            Ford Motor     201000   4596.0  237951             32.0

In [31]:
fortune['Profits'].rank(ascending=False).head(10)

Rank
1      11.0
2       3.0
3       1.0
4      27.0
5     102.0
6      33.0
7      44.0
8      21.0
9      14.0
10     52.0
Name: Profits, dtype: float64

In [32]:
fortune['rankByProfits'] = fortune['Profits'].rank(ascending=False)

In [33]:
fortune.head(10)

Title  Employees  Profits  Assets  rankByEmployees  \
Rank                                                                    
1                Walmart    2300000  13643.0  198825              1.0   
2     Berkshire Hathaway     367700  24074.0  620854              7.0   
3                  Apple     116000  45687.0  321686             57.0   
4            Exxon Mobil      72700   7840.0  330314             94.0   
5               McKesson      68000   2258.0   56563            104.5   
6     UnitedHealth Group     230000   7017.0  122810             23.0   
7             CVS Health     204000   5317.0   94462             30.0   
8         General Motors     225000   9427.0  221690             25.0   
9                   AT&T     268540  12976.0  403821             16.0   
10            Ford Motor     201000   4596.0  237951             32.0   

      rankByProfits  
Rank                 
1              11.0  
2               3.0  
3               1.0  
4              27.0  
5             102.0  
6              33.0  
7              44.0  
8              21.0  
9              14.0  
10             52.0

In [34]:
isEmployeesRankFirst10 = fortune['rankByEmployees'] <= 10

In [35]:
isProfitRankFirst10 = fortune['rankByProfits'] <= 10

In [36]:
fortune[isEmployeesRankFirst10 & isProfitRankFirst10]

Title  Employees  Profits  Assets  rankByEmployees  \
Rank                                                                    
2     Berkshire Hathaway     367700  24074.0  620854              7.0   

      rankByProfits  
Rank                 
2               3.0

In [37]:
isEmployeesRankMore400 = fortune['rankByEmployees'] > 400

In [38]:
fortune[isEmployeesRankMore400 & isProfitRankFirst10]

Title  Employees  Profits  Assets  rankByEmployees  rankByProfits
Rank                                                                          
148   Altria Group       8300  14239.0   45932            424.0           10.0

# Filtrowanie .where i .query

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [39]:
mcd = pd.read_csv("./data/mcdonalds.csv", usecols=["Item","Category", "Serving Size", "Calories", "TotalFat"])

In [40]:
ha400CalOrMore = mcd['Calories'] >= 400

In [41]:
mcd.where(ha400CalOrMore).head(10)

Category                                               Item  \
0        NaN                                                NaN   
1        NaN                                                NaN   
2        NaN                                                NaN   
3  Breakfast                          Sausage McMuffin with Egg   
4  Breakfast                   Sausage McMuffin with Egg Whites   
5  Breakfast                               Steak & Egg McMuffin   
6  Breakfast      Bacon, Egg & Cheese Biscuit (Regular Biscuit)   
7  Breakfast        Bacon, Egg & Cheese Biscuit (Large Biscuit)   
8  Breakfast  Bacon, Egg & Cheese Biscuit with Egg Whites (R...   
9  Breakfast  Bacon, Egg & Cheese Biscuit with Egg Whites (L...   

     Serving Size  Calories  TotalFat  
0             NaN       NaN       NaN  
1             NaN       NaN       NaN  
2             NaN       NaN       NaN  
3  5.7 oz (161 g)     450.0      28.0  
4  5.7 oz (161 g)     400.0      23.0  
5  6.5 oz (185 g)     430.0      23.0  
6  5.3 oz (150 g)     460.0      26.0  
7  5.8 oz (164 g)     520.0      30.0  
8  5.4 oz (153 g)     410.0      20.0  
9  5.9 oz (167 g)     470.0      25.0

Filtrowanie wcześniejszym sposobem tworzyło nowy dataFrame tylko z wartościami spełniającymi kryteria.
<br> W przypadku .where wyświetlany jest cały dataFrame, aczkolwiek w mejsca, gdzie nie były spełnione warunki wpisane jest NaN. Żeby się pozbyć wartości NaN z dataFrame użyjemy funkcji dropna()

In [44]:
mcd.where(ha400CalOrMore).dropna().head()

Category                                           Item    Serving Size  \
3  Breakfast                      Sausage McMuffin with Egg  5.7 oz (161 g)   
4  Breakfast               Sausage McMuffin with Egg Whites  5.7 oz (161 g)   
5  Breakfast                           Steak & Egg McMuffin  6.5 oz (185 g)   
6  Breakfast  Bacon, Egg & Cheese Biscuit (Regular Biscuit)  5.3 oz (150 g)   
7  Breakfast    Bacon, Egg & Cheese Biscuit (Large Biscuit)  5.8 oz (164 g)   

   Calories  TotalFat  
3     450.0      28.0  
4     400.0      23.0  
5     430.0      23.0  
6     460.0      26.0  
7     520.0      30.0

### .query()
w () wpisujemy wyrażenia (kryteria), którymi chcemy filtrować tak jak w jezyku SQL.
<br> nazwy kolumny po której filtrujemy nie bierzemy w ()

In [45]:
mcd.query('Category == "Desserts"').head()

Category                   Item     Serving Size  Calories  TotalFat
103  Desserts        Baked Apple Pie    2.7 oz (77 g)       250      13.0
104  Desserts  Chocolate Chip Cookie  1 cookie (33 g)       160       8.0
105  Desserts  Oatmeal Raisin Cookie  1 cookie (33 g)       150       6.0
106  Desserts    Kids Ice Cream Cone      1 oz (29 g)        45       1.5
107  Desserts       Hot Fudge Sundae   6.3 oz (179 g)       330       9.0

"in" oznacza to samo co: ('Category == "Desserts" | Category == "Beverages"')

In [48]:
mcd.query('Category in ["Desserts", "Beverages"]').head(20)

Category                        Item     Serving Size  Calories  \
103   Desserts             Baked Apple Pie    2.7 oz (77 g)       250   
104   Desserts       Chocolate Chip Cookie  1 cookie (33 g)       160   
105   Desserts       Oatmeal Raisin Cookie  1 cookie (33 g)       150   
106   Desserts         Kids Ice Cream Cone      1 oz (29 g)        45   
107   Desserts            Hot Fudge Sundae   6.3 oz (179 g)       330   
108   Desserts          Hot Caramel Sundae   6.4 oz (182 g)       340   
109   Desserts           Strawberry Sundae   6.3 oz (178 g)       280   
110  Beverages   Coca-Cola Classic (Small)     16 fl oz cup       140   
111  Beverages  Coca-Cola Classic (Medium)     21 fl oz cup       200   
112  Beverages   Coca-Cola Classic (Large)     30 fl oz cup       280   
113  Beverages   Coca-Cola Classic (Child)     12 fl oz cup       100   
114  Beverages           Diet Coke (Small)     16 fl oz cup         0   
115  Beverages          Diet Coke (Medium)     21 fl oz cup         0   
116  Beverages           Diet Coke (Large)     30 fl oz cup         0   
117  Beverages           Diet Coke (Child)     12 fl oz cup         0   
118  Beverages           Dr Pepper (Small)     16 fl oz cup       140   
119  Beverages          Dr Pepper (Medium)     21 fl oz cup       190   
120  Beverages           Dr Pepper (Large)     30 fl oz cup       270   
121  Beverages           Dr Pepper (Child)     12 fl oz cup       100   
122  Beverages      Diet Dr Pepper (Small)     16 fl oz cup         0   

     TotalFat  
103      13.0  
104       8.0  
105       6.0  
106       1.5  
107       9.0  
108       8.0  
109       6.0  
110       0.0  
111       0.0  
112       0.0  
113       0.0  
114       0.0  
115       0.0  
116       0.0  
117       0.0  
118       0.0  
119       0.0  
120       0.0  
121       0.0  
122       0.0

Możemy również od razu wpisywać więcej warunków.

In [50]:
mcd.query('Category == "Desserts" and Calories < 200').head()

Category                   Item     Serving Size  Calories  TotalFat
104  Desserts  Chocolate Chip Cookie  1 cookie (33 g)       160       8.0
105  Desserts  Oatmeal Raisin Cookie  1 cookie (33 g)       150       6.0
106  Desserts    Kids Ice Cream Cone      1 oz (29 g)        45       1.5

# Ćwiczenie
11 Metody where i query

In [51]:
import pandas as pd
import numpy as np

In [52]:
animals = pd.read_csv('./data/sleep_time.csv', index_col='ID').fillna(0)

Możemy od razu przy wczytywaniu danych wykorzystać funkcję .fillna(), aby zmienić wartości NaN na 0

In [53]:
animals.head(10)

name        genus   vore         order  \
ID                                                                 
1                      Cheetah     Acinonyx  carni     Carnivora   
2                   Owl monkey        Aotus   omni      Primates   
3              Mountain beaver   Aplodontia  herbi      Rodentia   
4   Greater short-tailed shrew      Blarina   omni  Soricomorpha   
5                          Cow          Bos  herbi  Artiodactyla   
6             Three-toed sloth     Bradypus  herbi        Pilosa   
7            Northern fur seal  Callorhinus  carni     Carnivora   
8                 Vesper mouse      Calomys      0      Rodentia   
9                          Dog        Canis  carni     Carnivora   
10                    Roe deer    Capreolus  herbi  Artiodactyla   

    conservation  sleep_total  sleep_rem  sleep_cycle  awake  brainwt   bodywt  
ID                                                                              
1             lc         12.1        0.0     0.000000   11.9  0.00000   50.000  
2              0         17.0        1.8     0.000000    7.0  0.01550    0.480  
3             nt         14.4        2.4     0.000000    9.6  0.00000    1.350  
4             lc         14.9        2.3     0.133333    9.1  0.00029    0.019  
5   domesticated          4.0        0.7     0.666667   20.0  0.42300  600.000  
6              0         14.4        2.2     0.766667    9.6  0.00000    3.850  
7             vu          8.7        1.4     0.383333   15.3  0.00000   20.490  
8              0          7.0        0.0     0.000000   17.0  0.00000    0.045  
9   domesticated         10.1        2.9     0.333333   13.9  0.07000   14.000  
10            lc          3.0        0.0     0.000000   21.0  0.09820   14.800

In [67]:
herbi = animals.where(animals['vore'] == "herbi")

In [60]:
len(herbi)

83

In [69]:
herbi = animals.where(animals['vore'] == "herbi").dropna()

In [70]:
len(herbi)

32

In [71]:
carni = animals.where(animals['vore'] == "carni").dropna()

In [72]:
len(carni)

19

In [73]:
omni = animals.where(animals['vore'] == "omni").dropna()

In [74]:
len(omni)

20

In [76]:
herbi['sleep_total'].mean()

9.509375

In [77]:
carni['sleep_total'].mean()

10.378947368421054

In [78]:
omni['sleep_total'].mean()

10.924999999999999

In [79]:
animals.query('sleep_total > 14')

name         genus     vore            order  \
ID                                                                           
2                       Owl monkey         Aotus     omni         Primates   
3                  Mountain beaver    Aplodontia    herbi         Rodentia   
4       Greater short-tailed shrew       Blarina     omni     Soricomorpha   
6                 Three-toed sloth      Bradypus    herbi           Pilosa   
18            Long-nosed armadillo       Dasypus    carni        Cingulata   
20          North American Opossum     Didelphis     omni  Didelphimorphia   
22                   Big brown bat     Eptesicus  insecti       Chiroptera   
27       Western american chipmunk      Eutamias    herbi         Rodentia   
37            Thick-tailed opposum    Lutreolina    carni  Didelphimorphia   
39                Mongolian gerbil      Meriones    herbi         Rodentia   
40                  Golden hamster  Mesocricetus    herbi         Rodentia   
43                Little brown bat        Myotis  insecti       Chiroptera   
44            Round-tailed muskrat      Neofiber    herbi         Rodentia   
47      Northern grasshopper mouse     Onychomys    carni         Rodentia   
51                           Tiger      Panthera    carni        Carnivora   
62                 Giant armadillo    Priodontes  insecti        Cingulata   
70          Arctic ground squirrel  Spermophilus    herbi         Rodentia   
72  Golden-mantled ground squirrel  Spermophilus    herbi         Rodentia   
76       Eastern american chipmunk        Tamias    herbi         Rodentia   
78                          Tenrec        Tenrec     omni     Afrosoricida   

   conservation  sleep_total  sleep_rem  sleep_cycle  awake  brainwt   bodywt  
ID                                                                             
2             0         17.0        1.8     0.000000    7.0  0.01550    0.480  
3            nt         14.4        2.4     0.000000    9.6  0.00000    1.350  
4            lc         14.9        2.3     0.133333    9.1  0.00029    0.019  
6             0         14.4        2.2     0.766667    9.6  0.00000    3.850  
18           lc         17.4        3.1     0.383333    6.6  0.01080    3.500  
20           lc         18.0        4.9     0.333333    6.0  0.00630    1.700  
22           lc         19.7        3.9     0.116667    4.3  0.00030    0.023  
27            0         14.9        0.0     0.000000    9.1  0.00000    0.071  
37           lc         19.4        6.6     0.000000    4.6  0.00000    0.370  
39           lc         14.2        1.9     0.000000    9.8  0.00000    0.053  
40           en         14.3        3.1     0.200000    9.7  0.00100    0.120  
43            0         19.9        2.0     0.200000    4.1  0.00025    0.010  
44           nt         14.6        0.0     0.000000    9.4  0.00000    0.266  
47           lc         14.5        0.0     0.000000    9.5  0.00000    0.028  
51           en         15.8        0.0     0.000000    8.2  0.00000  162.564  
62           en         18.1        6.1     0.000000    5.9  0.08100   60.000  
70           lc         16.6        0.0     0.000000    7.4  0.00570    0.920  
72           lc         15.9        3.0     0.000000    8.1  0.00000    0.205  
76            0         15.8        0.0     0.000000    8.2  0.00000    0.112  
78            0         15.6        2.3     0.000000    8.4  0.00260    0.900

In [80]:
animals.query('sleep_total > 14 and vore == "herbi"')

name         genus   vore     order  \
ID                                                                  
3                  Mountain beaver    Aplodontia  herbi  Rodentia   
6                 Three-toed sloth      Bradypus  herbi    Pilosa   
27       Western american chipmunk      Eutamias  herbi  Rodentia   
39                Mongolian gerbil      Meriones  herbi  Rodentia   
40                  Golden hamster  Mesocricetus  herbi  Rodentia   
44            Round-tailed muskrat      Neofiber  herbi  Rodentia   
70          Arctic ground squirrel  Spermophilus  herbi  Rodentia   
72  Golden-mantled ground squirrel  Spermophilus  herbi  Rodentia   
76       Eastern american chipmunk        Tamias  herbi  Rodentia   

   conservation  sleep_total  sleep_rem  sleep_cycle  awake  brainwt  bodywt  
ID                                                                            
3            nt         14.4        2.4     0.000000    9.6   0.0000   1.350  
6             0         14.4        2.2     0.766667    9.6   0.0000   3.850  
27            0         14.9        0.0     0.000000    9.1   0.0000   0.071  
39           lc         14.2        1.9     0.000000    9.8   0.0000   0.053  
40           en         14.3        3.1     0.200000    9.7   0.0010   0.120  
44           nt         14.6        0.0     0.000000    9.4   0.0000   0.266  
70           lc         16.6        0.0     0.000000    7.4   0.0057   0.920  
72           lc         15.9        3.0     0.000000    8.1   0.0000   0.205  
76            0         15.8        0.0     0.000000    8.2   0.0000   0.112

In [81]:
animals.query('sleep_total > 14 and vore == "herbi" and bodywt > 1')

name       genus   vore     order conservation  sleep_total  \
ID                                                                            
3    Mountain beaver  Aplodontia  herbi  Rodentia           nt         14.4   
6   Three-toed sloth    Bradypus  herbi    Pilosa            0         14.4   

    sleep_rem  sleep_cycle  awake  brainwt  bodywt  
ID                                                  
3         2.4     0.000000    9.6      0.0    1.35  
6         2.2     0.766667    9.6      0.0    3.85

# Metody .isin, .isnull, .notnull, .between (Filtrowanie)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [3]:
color = ['green', 'green', 'blue', 'blue', 'red', 'red', 'white']
size = ['S','S','S','M','M','M','L']
gender = ['M', 'W', 'M', 'W', 'M', 'W', 'U']
clothes = pd.DataFrame({'color':color, 'size':size, 'gender':gender})
clothes

color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W
6  white    L      U

In [4]:
isColorBlue = clothes['color'] == 'blue'
isColorGreen = clothes['color'] == 'green'
isColorRed = clothes['color'] == 'red'

#### .isin()

In [7]:
myColors = clothes['color'].isin(['blue', 'green', 'red'])

In [10]:
myColors

0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: color, dtype: bool

metoda .isin zwraca wartości True or False, ale wykorzystując przypisaną zmienną z nazwą dataFrame możemy wyświetlić od razu nowy dataFrame, który uwzględnia warunki zapisane w metodzie .isin

In [11]:
clothes[myColors]

color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W

#### .notnull()

In [12]:
clothes.loc[6, 'size'] = np.NaN

In [13]:
clothes

color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W
6  white  NaN      U

In [15]:
clothes['size'].notnull()

0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: size, dtype: bool

zwraca True tam gdzie jest podana jakaś wartość, false tam gdzie jest wartość NaN

#### .isnull()
przeciwieństwo .notnull()

In [16]:
clothes['size'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
Name: size, dtype: bool

In [17]:
sizeUnknow = clothes['size'].isnull()

In [18]:
clothes[sizeUnknow]

color size gender
6  white  NaN      U

#### .between()

In [20]:
mcd = pd.read_csv("./data/mcdonalds.csv", usecols=["Item","Category", "Serving Size", "Calories", "TotalFat"])

bez funkcji between zrobimy tak:

In [21]:
hasMoreThan300Cal = mcd['Calories'] >= 300
hasLessThan400Cal = mcd['Calories'] <= 400

In [22]:
mcd[hasMoreThan300Cal & hasLessThan400Cal].head()

Category                                            Item    Serving Size  \
0   Breakfast                                    Egg McMuffin  4.8 oz (136 g)   
2   Breakfast                                Sausage McMuffin  3.9 oz (111 g)   
4   Breakfast                Sausage McMuffin with Egg Whites  5.7 oz (161 g)   
20  Breakfast  Bacon, Egg & Cheese McGriddles with Egg Whites  6.3 oz (178 g)   
35  Breakfast                                        Hotcakes  5.3 oz (151 g)   

    Calories  TotalFat  
0        300      13.0  
2        370      23.0  
4        400      23.0  
20       400      15.0  
35       350       9.0

z funkcją between

In [23]:
caloriesBetween300and400 = mcd['Calories'].between(300, 400)

In [24]:
caloriesBetween300and400

0       True
1      False
2       True
3      False
4       True
       ...  
255    False
256    False
257     True
258    False
259    False
Name: Calories, Length: 260, dtype: bool

In [26]:
mcd[caloriesBetween300and400].head(10)

Category                                            Item  \
0        Breakfast                                    Egg McMuffin   
2        Breakfast                                Sausage McMuffin   
4        Breakfast                Sausage McMuffin with Egg Whites   
20       Breakfast  Bacon, Egg & Cheese McGriddles with Egg Whites   
35       Breakfast                                        Hotcakes   
37       Breakfast                                 Sausage Burrito   
52     Beef & Pork                                        McDouble   
58  Chicken & Fish        Premium Grilled Chicken Classic Sandwich   
66  Chicken & Fish                                       McChicken   
69  Chicken & Fish                         Buffalo Ranch McChicken   

      Serving Size  Calories  TotalFat  
0   4.8 oz (136 g)       300      13.0  
2   3.9 oz (111 g)       370      23.0  
4   5.7 oz (161 g)       400      23.0  
20  6.3 oz (178 g)       400      15.0  
35  5.3 oz (151 g)       350       9.0  
37  3.9 oz (111 g)       300      16.0  
52  5.2 oz (147 g)       380      17.0  
58    7 oz (200 g)       350       9.0  
66  5.1 oz (143 g)       360      16.0  
69  5.2 oz (148 g)       360      16.0

w jednej linii kodu:

In [27]:
mcd[mcd['Calories'].between(300, 400)].head(10)

Category                                            Item  \
0        Breakfast                                    Egg McMuffin   
2        Breakfast                                Sausage McMuffin   
4        Breakfast                Sausage McMuffin with Egg Whites   
20       Breakfast  Bacon, Egg & Cheese McGriddles with Egg Whites   
35       Breakfast                                        Hotcakes   
37       Breakfast                                 Sausage Burrito   
52     Beef & Pork                                        McDouble   
58  Chicken & Fish        Premium Grilled Chicken Classic Sandwich   
66  Chicken & Fish                                       McChicken   
69  Chicken & Fish                         Buffalo Ranch McChicken   

      Serving Size  Calories  TotalFat  
0   4.8 oz (136 g)       300      13.0  
2   3.9 oz (111 g)       370      23.0  
4   5.7 oz (161 g)       400      23.0  
20  6.3 oz (178 g)       400      15.0  
35  5.3 oz (151 g)       350       9.0  
37  3.9 oz (111 g)       300      16.0  
52  5.2 oz (147 g)       380      17.0  
58    7 oz (200 g)       350       9.0  
66  5.1 oz (143 g)       360      16.0  
69  5.2 oz (148 g)       360      16.0

# Ćwiczenie 
12. isin, isnull, notnull, between

In [28]:
fuel = pd.read_csv("./data/fuel.csv", usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)', 'Start Stop Technology'], low_memory=False)

In [29]:
listOfCars = ['Renault', 'Toyota', 'Ford']

In [30]:
isInList = fuel['Make'].isin(listOfCars)

In [32]:
isInList.head()

0    False
1    False
2    False
3    False
4    False
Name: Make, dtype: bool

In [34]:
fuel[isInList].head()

Vehicle ID  Year  Make       Model                        Class  \
668       27613  1984  Ford  Bronco 4WD  Special Purpose Vehicle 4WD   
669       27616  1984  Ford  Bronco 4WD  Special Purpose Vehicle 4WD   
670       27619  1984  Ford  Bronco 4WD  Special Purpose Vehicle 4WD   
671       27622  1984  Ford  Bronco 4WD  Special Purpose Vehicle 4WD   
672       28472  1984  Ford  Bronco 4WD  Special Purpose Vehicle 4WD   

    Fuel Type  Combined MPG (FT1) Start Stop Technology  
668   Regular                13.0                   NaN  
669   Regular                11.0                   NaN  
670   Regular                10.0                   NaN  
671   Regular                11.0                   NaN  
672   Regular                13.0                   NaN

In [35]:
isNoStartStopDefined = fuel['Start Stop Technology'].isnull()

In [36]:
fuel[isNoStartStopDefined].head(10)

Vehicle ID  Year                         Make               Model  \
0       26587  1984                   Alfa Romeo           GT V6 2.5   
1       27705  1984                   Alfa Romeo           GT V6 2.5   
2       26561  1984                   Alfa Romeo  Spider Veloce 2000   
3       27681  1984                   Alfa Romeo  Spider Veloce 2000   
4       27550  1984                   AM General   DJ Po Vehicle 2WD   
5       28426  1984                   AM General   DJ Po Vehicle 2WD   
6       27549  1984                   AM General    FJ8c Post Office   
7       28425  1984                   AM General    FJ8c Post Office   
8       27593  1984  American Motors Corporation           Eagle 4WD   
9       28455  1984  American Motors Corporation           Eagle 4WD   

                         Class Fuel Type  Combined MPG (FT1)  \
0             Minicompact Cars   Regular                20.0   
1             Minicompact Cars   Regular                20.0   
2                  Two Seaters   Regular                21.0   
3                  Two Seaters   Regular                21.0   
4  Special Purpose Vehicle 2WD   Regular                17.0   
5  Special Purpose Vehicle 2WD   Regular                17.0   
6  Special Purpose Vehicle 2WD   Regular                13.0   
7  Special Purpose Vehicle 2WD   Regular                13.0   
8  Special Purpose Vehicle 4WD   Regular                17.0   
9  Special Purpose Vehicle 4WD   Regular                17.0   

  Start Stop Technology  
0                   NaN  
1                   NaN  
2                   NaN  
3                   NaN  
4                   NaN  
5                   NaN  
6                   NaN  
7                   NaN  
8                   NaN  
9                   NaN

In [37]:
isStartStopDefined = fuel['Start Stop Technology'].notnull()

In [39]:
fuel[isStartStopDefined].head(10)

Vehicle ID  Year       Make                      Model  \
16448       30976  1998  Chevrolet               S10 Electric   
16449       30977  1998  Chevrolet               S10 Electric   
16711       30975  1998      Honda                    EV Plus   
17323       30973  1999      Dodge  Caravan/Grand Caravan 2WD   
17433       30971  1999       Ford          Ranger Pickup 2WD   
17434       30972  1999       Ford          Ranger Pickup 2WD   
17452       30968  1999        GMC                        EV1   
17453       30969  1999        GMC                        EV1   
17514       30970  1999      Honda                    EV Plus   
17756       30974  1999   Plymouth  Voyager/Grand Voyager 2WD   

                            Class    Fuel Type  Combined MPG (FT1)  \
16448     Small Pickup Trucks 2WD  Electricity                55.0   
16449     Small Pickup Trucks 2WD  Electricity                28.0   
16711                Compact Cars  Electricity                48.0   
17323               Minivan - 2WD  Electricity                35.0   
17433  Standard Pickup Trucks 2WD  Electricity                58.0   
17434  Standard Pickup Trucks 2WD  Electricity                47.0   
17452                 Two Seaters  Electricity                85.0   
17453                 Two Seaters  Electricity                37.0   
17514                Compact Cars  Electricity                48.0   
17756               Minivan - 2WD  Electricity                35.0   

      Start Stop Technology  
16448                     N  
16449                     N  
16711                     N  
17323                     N  
17433                     N  
17434                     N  
17452                     N  
17453                     N  
17514                     N  
17756                     N

In [41]:
mpg50_60 = fuel['Combined MPG (FT1)'].between(50,60)

In [42]:
fuel[mpg50_60].head(10)

Vehicle ID  Year       Make              Model  \
16448       30976  1998  Chevrolet       S10 Electric   
17433       30971  1999       Ford  Ranger Pickup 2WD   
18295       30966  2000       Ford  Ranger Pickup 2WD   
18296       30967  2000       Ford  Ranger Pickup 2WD   
18371       15606  2000      Honda            Insight   
19162       30965  2001       Ford  Ranger Pickup 2WD   
19240       16447  2001      Honda            Insight   
20178       17355  2002      Honda            Insight   
21192       18313  2003      Honda            Insight   
22264       19357  2004      Honda            Insight   

                            Class    Fuel Type  Combined MPG (FT1)  \
16448     Small Pickup Trucks 2WD  Electricity                55.0   
17433  Standard Pickup Trucks 2WD  Electricity                58.0   
18295  Standard Pickup Trucks 2WD  Electricity                58.0   
18296  Standard Pickup Trucks 2WD  Electricity                56.0   
18371                 Two Seaters      Regular                53.0   
19162  Standard Pickup Trucks 2WD  Electricity                58.0   
19240                 Two Seaters      Regular                53.0   
20178                 Two Seaters      Regular                53.0   
21192                 Two Seaters      Regular                53.0   
22264                 Two Seaters      Regular                52.0   

      Start Stop Technology  
16448                     N  
17433                     N  
18295                     N  
18296                     N  
18371                     Y  
19162                     N  
19240                     Y  
20178                     Y  
21192                     Y  
22264                     Y

In [49]:
print('There are %d cars within the list %s' % (len(fuel[isInList]), listOfCars))

There are 4376 cars within the list ['Renault', 'Toyota', 'Ford']


In [56]:
print('There are %d cars where Start/Stop technology is not determined'%len(fuel[isNoStartStopDefined]))
print('There are %d cars where Start/Stop technology is determined'%len(fuel[isStartStopDefined]))
print('There are %d cares with MPG value between 50 and 60'%len(fuel[mpg50_60]))

There are 31374 cars where Start/Stop technology is not determined
There are 310 cars where Start/Stop technology is determined
There are 13 cares with MPG value between 50 and 60


# Duplikaty
Jeżeli w dataFrame znajdują się powtarzające się dane, a my chcemy pracować tylko z unikalnymi danymi to je przetwarzamy.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [2]:
color = ['green', 'green', 'blue', 'blue', 'red', 'red', 'white']
size = ['S','S','S','M','M','M','L']
gender = ['M', 'W', 'M', 'W', 'M', 'W', 'U']
clothes = pd.DataFrame({'color':color, 'size':size, 'gender':gender})
clothes

color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W
6  white    L      U

In [4]:
clothes['color'].is_unique

False

#### .unique()
zwraca w formie listy wszystkie różne wartości występujące w danej kolumnie. Jeżeli mamy 4 razy 'red' i 3 razy 'blue' wyświetli raz red i raz blue

In [5]:
clothes['color'].unique()

array(['green', 'blue', 'red', 'white'], dtype=object)

#### .nunique()
obliczy ilość unikalnych obiektów. Omija wartości NaN

In [6]:
clothes['color'].nunique()

4

Jeśli chcemy policzyć również wartości NaN to używamy:

In [7]:
len(clothes['color'].unique())

4

#### .duplicated()
wykrywa, czy istnieją wartości, które się powielają. Domyślnie - .duplicated(keep='first')

In [8]:
clothes['color'].duplicated(keep='first')

0    False
1     True
2    False
3     True
4    False
5     True
6    False
Name: color, dtype: bool

.duplicated(keep='first') - zwraca False w miejscu, gdzie dana wartość występuje pierwszy raz. Tam gdzie wartość się duplikuje zwraca wartość True.

In [9]:
clothes['color'].duplicated(keep='last')

0     True
1    False
2     True
3    False
4     True
5    False
6    False
Name: color, dtype: bool

(keep='last') - True przy wszystkich wynikach, które się powtarzają, poza ostatnią. Ostatnia wartość przyjmuje wartość False, tak samo wartości, które się nie powtarzaja 

In [11]:
clothes['color'].duplicated(keep=False)

0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: color, dtype: bool

True przy wszytkich wartościach, które się powtarzają. False przy wartościach, które się nie powatrzają

In [16]:
uniqueValues = clothes['color'].duplicated(keep='first')
clothes[uniqueValues]    # wyświetli powtórzenia, lub clothes[~uniqueValues] wyświetli wszystkie pierwsze wystąpienia wartości

color size gender
1  green    S      W
3   blue    M      W
5    red    M      W

#### .drop_duplicates(subset=['color'], keep='first')

In [15]:
clothes.drop_duplicates(subset=['color'], keep='first')

color size gender
0  green    S      M
2   blue    S      M
4    red    M      M
6  white    L      U

zwrócone zostały wszystkie pierwsze wystąpienia

In [17]:
clothes.drop_duplicates(['color', 'size'])

color size gender
0  green    S      M
2   blue    S      M
3   blue    M      W
4    red    M      M
6  white    L      U

zwrócone zostały wszystkie elementy, gdzie nie powtarzały się elementy z obydwu kolumn (wiersz 1 jest taki jak 0, a wiesz 5 taki jak 4 - jeśli chodzi o kolumny color i size)

# Ćwiczenie 
13. Duplikaty w dataFrame

In [18]:
surveys = pd.read_csv('./data/StackOverflowDeveloperSurvey2018.csv', usecols=['Country','Gender','OperatingSystem'], low_memory=False)

In [19]:
surveys.head()

Country OperatingSystem Gender
0           Kenya     Linux-based   Male
1  United Kingdom     Linux-based   Male
2   United States             NaN    NaN
3   United States         Windows   Male
4    South Africa         Windows   Male

In [21]:
surveys['Country'].is_unique

False

In [25]:
surveys['Country'].unique()

array(['Kenya', 'United Kingdom', 'United States', 'South Africa',
       'Nigeria', 'India', 'Spain', 'Croatia', 'Netherlands', 'Israel',
       'Sweden', 'Chile', 'Australia', 'Greece', 'Poland', 'Belgium',
       'Argentina', 'Germany', 'Russian Federation', 'Indonesia',
       'Ireland', 'France', 'Ukraine', 'Denmark', 'Dominican Republic',
       'China', 'Latvia', 'Algeria', 'Colombia', 'Japan', 'Finland',
       'Romania', 'Brazil', 'Bulgaria', 'Iran, Islamic Republic of...',
       'Nepal', 'Bangladesh', 'Pakistan', 'Canada', 'Jordan', 'Portugal',
       'Italy', 'New Zealand', 'Turkey', 'Czech Republic', 'Viet Nam',
       'Austria', 'Egypt', 'Malaysia', 'Mozambique', 'Thailand',
       'Slovakia', 'Lebanon', 'Mexico', 'Hong Kong (S.A.R.)', 'Norway',
       'Myanmar', 'Switzerland', 'South Korea', 'Hungary', 'Armenia',
       'Kazakhstan', 'United Arab Emirates', 'Singapore', 'Qatar',
       'Bosnia and Herzegovina', 'Bahrain', 'Sri Lanka', 'Cambodia',
       'Serbia', 'Philip

In [26]:
surveys['Country'].nunique()

183

In [27]:
len(surveys['Country'].unique())

184

In [32]:
duplicatedKeepFirst = surveys['Country'].duplicated()    # lub surveys.duplicated('Country')

In [31]:
surveys[~duplicatedKeepFirst].head(10)

Country OperatingSystem  Gender
0            Kenya     Linux-based    Male
1   United Kingdom     Linux-based    Male
2    United States             NaN     NaN
4     South Africa         Windows    Male
7          Nigeria         Windows  Female
9            India             NaN     NaN
10           Spain             NaN     NaN
12         Croatia             NaN     NaN
14     Netherlands         Windows    Male
15          Israel             NaN     NaN

In [33]:
len(surveys[~duplicatedKeepFirst])

184

In [35]:
surveys.drop_duplicates(['Country', 'OperatingSystem'], inplace=True)

In [36]:
surveys.query('Country =="Poland"')

Country OperatingSystem Gender
30     Poland     Linux-based   Male
34     Poland         Windows   Male
232    Poland             NaN    NaN
854    Poland           MacOS   Male
72587  Poland        BSD/Unix    NaN